export interface CatalogProduct {
  id: string;
  name_fr: string;
  name_en: string;
  categorySlug: string;
  price: number;
  cost: number;
  photoKeyword: string;
  short_fr: string;
  short_en: string;
  desc_fr: string;
  desc_en: string;
  benefits_fr: string[];
  benefits_en: string[];
  args_fr: string[];
  args_en: string[];
  tags: string[];
  trendScore: number;
  keywords: string[]; // for trend matching
}

export const PRODUCT_CATALOG: CatalogProduct[] = [
  // ── gadgets-voiture ──────────────────────────────────────────────────────────
  {
    id: "gv-01", name_fr: "Support Téléphone Voiture Magnétique 360°", name_en: "Magnetic Car Phone Holder 360° Rotation",
    categorySlug: "gadgets-voiture", price: 19.99, cost: 3.50, photoKeyword: "magnetic car phone mount holder dashboard",
    short_fr: "Support magnétique ultra-puissant, rotation 360°, compatible tous smartphones.",
    short_en: "Ultra-strong magnetic mount, 360° rotation, compatible with all smartphones.",
    desc_fr: "<p>Ce support téléphone magnétique révolutionne votre expérience de conduite. Grâce à ses 6 aimants ultra-puissants, votre téléphone reste en place même sur les routes les plus accidentées.</p><p>Installation en 3 secondes sur grille d'aération ou tableau de bord. Compatible avec tous les smartphones de 4 à 6,9 pouces.</p>",
    desc_en: "<p>This magnetic phone mount revolutionizes your driving experience. With 6 ultra-powerful magnets, your phone stays in place even on bumpy roads.</p><p>3-second installation on air vent or dashboard. Compatible with all smartphones from 4 to 6.9 inches.</p>",
    benefits_fr: ["6 aimants ultra-puissants", "Rotation 360° ajustable", "Installation sans outils", "Compatible induction QI", "Livraison sous 7-14 jours"],
    benefits_en: ["6 ultra-powerful magnets", "360° adjustable rotation", "Tool-free installation", "QI wireless compatible", "Delivery in 7-14 days"],
    args_fr: ["Mains libres légal en France", "Fonctionne avec coque", "Très facile à utiliser"],
    args_en: ["Hands-free legally required", "Works with phone case", "Super easy to use"],
    tags: ["voiture", "support", "téléphone", "magnétique"], trendScore: 82, keywords: ["voiture", "car", "driving", "phone", "holder", "mount"],
  },
  {
    id: "gv-02", name_fr: "Chargeur Voiture Sans Fil 15W Charge Rapide", name_en: "15W Fast Wireless Car Charger",
    categorySlug: "gadgets-voiture", price: 29.99, cost: 7.00, photoKeyword: "wireless car charger fast charging mount",
    short_fr: "Charge rapide 15W sans fil pour tous smartphones compatibles QI, fixation grille d'aération.",
    short_en: "15W fast wireless charging for all QI-compatible smartphones, air vent mount.",
    desc_fr: "<p>Chargez votre téléphone en conduisant sans vous soucier des câbles. Ce chargeur sans fil 15W supporte la charge rapide Magsafe, Samsung Fast Charging et Qi standard.</p><p>S'installe en 30 secondes sur la grille d'aération. LED indicateur de charge.</p>",
    desc_en: "<p>Charge your phone while driving without worrying about cables. This 15W wireless charger supports MagSafe fast charging, Samsung Fast Charging, and standard Qi.</p><p>Installs in 30 seconds on the air vent. LED charge indicator.</p>",
    benefits_fr: ["Charge rapide 15W sans fil", "Compatible MagSafe & Samsung", "Fixation magnétique stable", "Pas de câble à brancher", "Auto-clamping intelligent"],
    benefits_en: ["15W wireless fast charge", "MagSafe & Samsung compatible", "Stable magnetic mount", "No cable needed", "Smart auto-clamping"],
    args_fr: ["Compatible 99% smartphones récents", "Économise la batterie en route", "Discret et élégant"],
    args_en: ["Compatible 99% recent smartphones", "Keeps battery full on route", "Sleek and discreet"],
    tags: ["chargeur", "voiture", "sans-fil", "rapide"], trendScore: 85, keywords: ["chargeur", "wireless", "charge", "voiture", "car charger"],
  },
  {
    id: "gv-03", name_fr: "Aspirateur Voiture Portable 12V 6000Pa", name_en: "Portable Car Vacuum Cleaner 12V 6000Pa",
    categorySlug: "gadgets-voiture", price: 34.99, cost: 8.50, photoKeyword: "portable car vacuum cleaner 12v handheld",
    short_fr: "Aspirateur voiture puissant 6000Pa, branchement allume-cigare, kit 3 embouts.",
    short_en: "Powerful 6000Pa car vacuum, cigarette lighter plug, 3 attachment kit.",
    desc_fr: "<p>Gardez votre voiture impeccable avec cet aspirateur 12V ultra-puissant. 6000Pa de succion pour aspirer miettes, poils d'animaux et poussière en quelques secondes.</p><p>Câble de 5 mètres pour atteindre tous les recoins. Filtre lavable.</p>",
    desc_en: "<p>Keep your car immaculate with this ultra-powerful 12V vacuum. 6000Pa suction to remove crumbs, pet hair, and dust in seconds.</p><p>5-meter cable to reach every corner. Washable filter.</p>",
    benefits_fr: ["6000Pa aspiration puissante", "Câble 5m pour tout atteindre", "Filtre lavable réutilisable", "3 embouts inclus", "Silencieux 72dB"],
    benefits_en: ["6000Pa powerful suction", "5m cable to reach everywhere", "Washable reusable filter", "3 attachments included", "Quiet 72dB"],
    args_fr: ["Idéal familles avec enfants/animaux", "Fonctionne sur allume-cigare", "Nettoyage express 5 min"],
    args_en: ["Perfect for families with kids/pets", "Works on cigarette lighter", "Quick 5-minute clean"],
    tags: ["aspirateur", "voiture", "portable", "nettoyage"], trendScore: 75, keywords: ["aspirateur", "vacuum", "voiture", "car", "cleaning"],
  },
  {
    id: "gv-04", name_fr: "Organisateur Siège Arrière Voiture Multipoches", name_en: "Back Seat Car Organizer Multi-Pocket",
    categorySlug: "gadgets-voiture", price: 22.99, cost: 5.00, photoKeyword: "car back seat organizer storage pockets",
    short_fr: "Organisateur voiture 8 poches, imperméable, idéal famille avec enfants.",
    short_en: "8-pocket car organizer, waterproof, ideal for families with children.",
    desc_fr: "<p>Finies les voitures en désordre ! Cet organisateur de siège arrière 8 poches garde tout à portée de main pour vos enfants et passagers.</p><p>Tissu Oxford imperméable, installation en 2 minutes sur appui-tête. Tablette plateau pliable incluse.</p>",
    desc_en: "<p>No more messy cars! This 8-pocket back seat organizer keeps everything within reach for your children and passengers.</p><p>Waterproof Oxford fabric, 2-minute installation on headrest. Folding tray included.</p>",
    benefits_fr: ["8 poches de rangement", "Tissu Oxford imperméable", "Tablette pliable incluse", "Installation 2 minutes", "Compatible toutes voitures"],
    benefits_en: ["8 storage pockets", "Waterproof Oxford fabric", "Folding tray included", "2-minute installation", "Universal fit"],
    args_fr: ["Indispensable pour les familles", "Enfants accessibles en route", "Résistant et durable"],
    args_en: ["Essential for families", "Kids can reach everything on the go", "Durable and resistant"],
    tags: ["organisateur", "voiture", "rangement", "famille"], trendScore: 72, keywords: ["organisateur", "organizer", "voiture", "car", "rangement", "storage"],
  },
  {
    id: "gv-05", name_fr: "Dashcam Full HD 1080P Grand Angle 170°", name_en: "Full HD 1080P 170° Wide Angle Dashcam",
    categorySlug: "gadgets-voiture", price: 44.99, cost: 11.00, photoKeyword: "dashcam car camera full hd wide angle",
    short_fr: "Caméra tableau de bord Full HD 1080P, vision nocturne, grand angle 170°, détection choc.",
    short_en: "Full HD 1080P dashcam, night vision, 170° wide angle, shock detection.",
    desc_fr: "<p>Protégez-vous en cas d'accident avec cette dashcam Full HD. Enregistrement en boucle automatique, vision nocturne avancée et détection de choc G-sensor.</p><p>Écran 3 pouces, installation rapide pare-brise. Carte mémoire jusqu'à 128Go.</p>",
    desc_en: "<p>Protect yourself in case of accidents with this Full HD dashcam. Automatic loop recording, advanced night vision, and G-sensor shock detection.</p><p>3-inch screen, quick windshield installation. Memory card up to 128GB.</p>",
    benefits_fr: ["Résolution Full HD 1080P", "Vision nocturne WDR", "Détection choc G-sensor", "Enregistrement boucle auto", "Grand angle 170°"],
    benefits_en: ["Full HD 1080P resolution", "WDR night vision", "G-sensor shock detection", "Auto loop recording", "170° wide angle"],
    args_fr: ["Preuve irréfutable en cas d'accident", "Dissuade les infractions", "Assurance peut exiger"],
    args_en: ["Irrefutable proof in accidents", "Deters traffic violations", "Insurance companies approve"],
    tags: ["dashcam", "caméra", "voiture", "sécurité"], trendScore: 80, keywords: ["dashcam", "caméra", "camera", "voiture", "car", "sécurité", "accident"],
  },

  // ── maison-intelligente ───────────────────────────────────────────────────────
  {
    id: "mi-01", name_fr: "Ampoule LED Connectée WiFi RGB E27 10W", name_en: "WiFi RGB Smart LED Bulb E27 10W",
    categorySlug: "maison-intelligente", price: 16.99, cost: 3.50, photoKeyword: "smart wifi rgb led bulb e27 color",
    short_fr: "Ampoule connectée 16 millions de couleurs, contrôle vocal Alexa/Google, app smartphone.",
    short_en: "Smart bulb with 16 million colors, Alexa/Google voice control, smartphone app.",
    desc_fr: "<p>Transformez votre maison en maison intelligente avec ces ampoules WiFi RGB. 16 millions de couleurs, programmation horaire, mode ambiance et contrôle vocal compatible Alexa et Google Home.</p><p>Durée de vie 25 000h, équivalent 60W.</p>",
    desc_en: "<p>Transform your home into a smart home with these WiFi RGB bulbs. 16 million colors, scheduling, ambiance modes, and voice control compatible with Alexa and Google Home.</p><p>25,000h lifespan, 60W equivalent.</p>",
    benefits_fr: ["16 millions de couleurs", "Alexa & Google Home", "Programmation horaire", "25 000h durée de vie", "Aucun hub requis"],
    benefits_en: ["16 million colors", "Alexa & Google Home", "Scheduling", "25,000h lifespan", "No hub required"],
    args_fr: ["Remplace toute ampoule E27", "Économise 80% d'énergie", "Contrôle depuis partout"],
    args_en: ["Replaces any E27 bulb", "Saves 80% energy", "Control from anywhere"],
    tags: ["ampoule", "connectée", "rgb", "smart"], trendScore: 83, keywords: ["ampoule", "bulb", "smart", "connectée", "connected", "rgb", "alexa", "google"],
  },
  {
    id: "mi-02", name_fr: "Prise Connectée WiFi Compteur d'Énergie", name_en: "WiFi Smart Plug with Energy Monitor",
    categorySlug: "maison-intelligente", price: 14.99, cost: 3.00, photoKeyword: "smart plug wifi energy monitor power",
    short_fr: "Prise intelligente WiFi avec compteur consommation, programmable, compatible Alexa.",
    short_en: "WiFi smart plug with energy monitor, programmable, Alexa compatible.",
    desc_fr: "<p>Rendez n'importe quel appareil intelligent avec cette prise connectée WiFi. Mesurez votre consommation en temps réel, programmez des horaires et pilotez depuis votre smartphone partout dans le monde.</p>",
    desc_en: "<p>Make any appliance smart with this WiFi smart plug. Measure your consumption in real-time, set schedules, and control from your smartphone anywhere in the world.</p>",
    benefits_fr: ["Contrôle à distance 24/7", "Compteur consommation temps réel", "Programmation horaire", "Compatible Alexa/Google", "Installation 30 secondes"],
    benefits_en: ["24/7 remote control", "Real-time energy monitor", "Schedule programming", "Alexa/Google compatible", "30-second setup"],
    args_fr: ["Économies sur facture d'énergie", "Aucune installation électrique", "Pack de 4 disponible"],
    args_en: ["Save on energy bills", "No electrical installation", "Pack of 4 available"],
    tags: ["prise", "connectée", "wifi", "énergie"], trendScore: 79, keywords: ["prise", "plug", "smart", "connectée", "wifi", "énergie", "energy"],
  },
  {
    id: "mi-03", name_fr: "Robot Aspirateur Cartographie Laser 2700Pa", name_en: "Laser Mapping Robot Vacuum 2700Pa",
    categorySlug: "maison-intelligente", price: 189.99, cost: 55.00, photoKeyword: "robot vacuum cleaner laser navigation mapping",
    short_fr: "Robot aspirateur avec cartographie laser LiDAR, 2700Pa, programmation zones, vidage automatique.",
    short_en: "Robot vacuum with LiDAR laser mapping, 2700Pa, zone scheduling, auto-empty.",
    desc_fr: "<p>Ce robot aspirateur haut de gamme crée une carte précise de votre maison grâce à la technologie LiDAR. Zones d'exclusion, nettoyage par pièce, 2700Pa de succion pour tapis épais.</p><p>Autonomie 180 minutes, contrôle par application ou voix.</p>",
    desc_en: "<p>This premium robot vacuum creates a precise map of your home using LiDAR technology. Exclusion zones, room-by-room cleaning, 2700Pa suction for thick carpets.</p><p>180-minute battery, app or voice control.</p>",
    benefits_fr: ["Cartographie LiDAR précise", "2700Pa aspiration puissante", "180 min autonomie", "Zones d'exclusion", "Compatible tapis épais"],
    benefits_en: ["Precise LiDAR mapping", "2700Pa strong suction", "180 min battery", "Exclusion zones", "Works on thick carpets"],
    args_fr: ["Économise 4h de ménage/semaine", "Fonctionne pendant votre travail", "Retour base automatique"],
    args_en: ["Saves 4h of cleaning/week", "Works while you're at work", "Auto-return to base"],
    tags: ["robot", "aspirateur", "intelligent", "laser"], trendScore: 90, keywords: ["robot", "aspirateur", "vacuum", "smart", "maison"],
  },
  {
    id: "mi-04", name_fr: "Caméra Surveillance Intérieure WiFi 360° 2K", name_en: "Indoor WiFi Security Camera 360° 2K",
    categorySlug: "maison-intelligente", price: 39.99, cost: 9.00, photoKeyword: "indoor security camera wifi 360 2k",
    short_fr: "Caméra IP 2K 360°, vision nocturne couleur, détection IA, alerte smartphone, stockage cloud.",
    short_en: "2K 360° IP camera, color night vision, AI detection, phone alerts, cloud storage.",
    desc_fr: "<p>Surveillez votre domicile à tout moment avec cette caméra IP 2K ultra-nette. Détection intelligente des personnes et animaux, vision nocturne couleur à 10m, rotation motorisée 360°.</p>",
    desc_en: "<p>Monitor your home at any time with this ultra-sharp 2K IP camera. Smart person and pet detection, 10m color night vision, motorized 360° rotation.</p>",
    benefits_fr: ["Résolution 2K ultra-nette", "Vision nocturne couleur", "Détection IA personnes", "Rotation 360° motorisée", "Stockage cloud & SD card"],
    benefits_en: ["Ultra-sharp 2K resolution", "Color night vision", "AI person detection", "Motorized 360° rotation", "Cloud & SD card storage"],
    args_fr: ["Surveillance 24/7 en déplacement", "Alerte instantanée sur mobile", "Facile à installer"],
    args_en: ["24/7 monitoring while away", "Instant mobile alerts", "Easy to install"],
    tags: ["caméra", "surveillance", "smart", "sécurité"], trendScore: 84, keywords: ["caméra", "camera", "surveillance", "security", "smart", "maison", "home"],
  },
  {
    id: "mi-05", name_fr: "Diffuseur Huiles Essentielles Ultrason 500ml", name_en: "500ml Ultrasonic Essential Oil Diffuser",
    categorySlug: "maison-intelligente", price: 34.99, cost: 8.00, photoKeyword: "ultrasonic essential oil diffuser humidifier bedroom",
    short_fr: "Diffuseur ultrason 500ml, 7 couleurs LED, minuterie 1-6h, silencieux, humidificateur.",
    short_en: "500ml ultrasonic diffuser, 7 LED colors, 1-6h timer, silent, humidifier.",
    desc_fr: "<p>Créez une atmosphère relaxante chez vous avec ce diffuseur ultrasonique 500ml. Silencieux (30dB), 7 couleurs LED dimmables, minuterie 1h à 6h, fonctionne également comme humidificateur d'air.</p>",
    desc_en: "<p>Create a relaxing atmosphere at home with this 500ml ultrasonic diffuser. Silent (30dB), 7 dimmable LED colors, 1h to 6h timer, also works as an air humidifier.</p>",
    benefits_fr: ["500ml grande contenance", "7 couleurs LED dimmables", "Silencieux 30dB", "Minuterie 1-6 heures", "Arrêt automatique sécurité"],
    benefits_en: ["500ml large capacity", "7 dimmable LED colors", "Silent 30dB", "1-6 hour timer", "Auto safety shutoff"],
    args_fr: ["Améliore qualité de l'air", "Aide au sommeil", "Cadeau idéal"],
    args_en: ["Improves air quality", "Helps with sleep", "Perfect gift"],
    tags: ["diffuseur", "aromathérapie", "huiles", "bien-être"], trendScore: 76, keywords: ["diffuseur", "diffuser", "aromathérapie", "aromatherapy", "bien-être", "wellness"],
  },

  // ── cuisine-pratique ──────────────────────────────────────────────────────────
  {
    id: "cp-01", name_fr: "Friteuse à Air Chaud 5L Numérique Écran Tactile", name_en: "5L Digital Air Fryer Touchscreen",
    categorySlug: "cuisine-pratique", price: 69.99, cost: 18.00, photoKeyword: "digital air fryer 5l touchscreen kitchen",
    short_fr: "Friteuse air 5L, 8 programmes préréglés, écran tactile, zéro huile, jusqu'à 200°C.",
    short_en: "5L air fryer, 8 preset programs, touchscreen, zero oil, up to 200°C.",
    desc_fr: "<p>Cuisinez des plats croustillants sans matière grasse avec cette friteuse à air 5L. 8 programmes préréglés (frites, poulet, poisson, légumes...), écran tactile intuitif, température jusqu'à 200°C.</p><p>Panier antiadhésif compatible lave-vaisselle.</p>",
    desc_en: "<p>Cook crispy dishes with no oil using this 5L air fryer. 8 preset programs (fries, chicken, fish, vegetables...), intuitive touchscreen, temperature up to 200°C.</p><p>Dishwasher-safe non-stick basket.</p>",
    benefits_fr: ["Zéro huile, -80% calories", "8 programmes préréglés", "Capacité familiale 5L", "Nettoyage lave-vaisselle", "Cuisson 30% plus rapide"],
    benefits_en: ["Zero oil, -80% calories", "8 preset programs", "Family size 5L", "Dishwasher safe", "30% faster cooking"],
    args_fr: ["Tendance alimentation saine 2026", "Économise l'huile et l'argent", "Viral TikTok recettes"],
    args_en: ["Healthy eating trend 2026", "Save on oil and money", "TikTok recipe viral"],
    tags: ["friteuse", "air", "cuisine", "healthy"], trendScore: 92, keywords: ["friteuse", "fryer", "air fryer", "cuisine", "kitchen", "healthy", "sain"],
  },
  {
    id: "cp-02", name_fr: "Robot Cuisine Multifonction 1500W 8-en-1", name_en: "8-in-1 Multifunction Food Processor 1500W",
    categorySlug: "cuisine-pratique", price: 89.99, cost: 22.00, photoKeyword: "food processor multifunctional blender kitchen",
    short_fr: "Robot cuisine 8-en-1 : mixer, hacher, pétrir, râper, trancher. 1500W, bol 3L.",
    short_en: "8-in-1 food processor: blend, chop, knead, grate, slice. 1500W, 3L bowl.",
    desc_fr: "<p>Remplacez 8 appareils avec ce robot cuisine multifonction 1500W. Mixeur, hachoir, pétrisseur, râpe, éminceur, centrifugeuse... Bol en verre 3L résistant aux chocs, 12 vitesses.</p>",
    desc_en: "<p>Replace 8 appliances with this 1500W multifunction food processor. Blender, chopper, kneader, grater, slicer, juicer... 3L shockproof glass bowl, 12 speeds.</p>",
    benefits_fr: ["Remplace 8 appareils cuisine", "1500W moteur puissant", "Bol verre 3L incassable", "12 vitesses + pulse", "Garantie 2 ans"],
    benefits_en: ["Replaces 8 kitchen appliances", "1500W powerful motor", "3L shockproof glass bowl", "12 speeds + pulse", "2-year warranty"],
    args_fr: ["Économie d'espace et d'argent", "Repas prêts 3x plus vite", "Idéal familles actives"],
    args_en: ["Saves space and money", "Meals ready 3x faster", "Perfect for busy families"],
    tags: ["robot", "cuisine", "multifonction", "mixeur"], trendScore: 80, keywords: ["robot", "cuisine", "kitchen", "mixeur", "blender", "processor"],
  },
  {
    id: "cp-03", name_fr: "Balance Cuisine Numérique Précision 0.1g", name_en: "Digital Kitchen Scale Precision 0.1g",
    categorySlug: "cuisine-pratique", price: 14.99, cost: 3.00, photoKeyword: "digital kitchen scale precision baking",
    short_fr: "Balance cuisine haute précision 0.1g, 5kg max, tare, inox, 4 unités mesure.",
    short_en: "High precision kitchen scale 0.1g, 5kg max, tare, stainless steel, 4 units.",
    desc_fr: "<p>Précision absolue pour toutes vos recettes avec cette balance numérique. Plateau inox résistant, tare automatique, 4 unités (g/kg/oz/lb), affichage LCD rétroéclairé. Idéale pâtisserie et régimes alimentaires.</p>",
    desc_en: "<p>Absolute precision for all your recipes with this digital scale. Resistant stainless steel plate, auto tare, 4 units (g/kg/oz/lb), backlit LCD display. Perfect for baking and diets.</p>",
    benefits_fr: ["Précision 0.1g professionnelle", "Plateau inox résistant", "Tare automatique", "4 unités de mesure", "Pile incluse"],
    benefits_en: ["Professional 0.1g precision", "Resistant stainless steel", "Auto tare function", "4 measurement units", "Battery included"],
    args_fr: ["Indispensable pâtisserie", "Parfait régimes alimentaires", "Cadeau pas cher utile"],
    args_en: ["Essential for baking", "Perfect for diets", "Affordable useful gift"],
    tags: ["balance", "cuisine", "précision", "mesure"], trendScore: 68, keywords: ["balance", "scale", "cuisine", "kitchen", "mesure", "pâtisserie", "baking"],
  },
  {
    id: "cp-04", name_fr: "Centrifugeuse à Froid 150W Jus Frais", name_en: "150W Cold Press Slow Juicer",
    categorySlug: "cuisine-pratique", price: 79.99, cost: 20.00, photoKeyword: "slow juicer cold press fruits vegetables",
    short_fr: "Extracteur de jus à froid, préserve vitamines, silencieux, nettoyage facile.",
    short_en: "Cold press slow juicer, preserves vitamins, silent, easy to clean.",
    desc_fr: "<p>Profitez de jus de fruits et légumes 100% naturels avec cet extracteur à froid. La rotation lente 80 tr/min préserve jusqu'à 3x plus de vitamines qu'une centrifugeuse classique. Silencieux 60dB.</p>",
    desc_en: "<p>Enjoy 100% natural fruit and vegetable juices with this cold press juicer. Slow 80 RPM rotation preserves up to 3x more vitamins than a regular juicer. Quiet 60dB.</p>",
    benefits_fr: ["3x plus de vitamines préservées", "Silencieux 60dB", "Nettoyage 3 minutes", "Compatible fruits & légumes", "Anti-oxydation"],
    benefits_en: ["3x more vitamins preserved", "Quiet 60dB", "3-minute cleaning", "Fruits & vegetables", "Anti-oxidation"],
    args_fr: ["Tendance healthy 2026", "Économise abonnements jus bar", "Viral TikTok detox"],
    args_en: ["Healthy trend 2026", "Saves juice bar subscriptions", "TikTok detox viral"],
    tags: ["centrifugeuse", "jus", "sain", "vitamines"], trendScore: 78, keywords: ["jus", "juice", "detox", "sain", "healthy", "centrifugeuse", "vitamines"],
  },
  {
    id: "cp-05", name_fr: "Moule à Gâteau Silicone Set 6 Pièces Antiadhésif", name_en: "6-Piece Silicone Cake Mold Set Non-Stick",
    categorySlug: "cuisine-pratique", price: 24.99, cost: 5.50, photoKeyword: "silicone cake mold baking set non-stick",
    short_fr: "Set 6 moules silicone alimentaire, résistant -40°C à 230°C, sans BPA, démoulage parfait.",
    short_en: "6 food-grade silicone molds, resistant -40°C to 230°C, BPA-free, perfect release.",
    desc_fr: "<p>Réussissez tous vos gâteaux avec ce set de 6 moules silicone alimentaire certifiés. Démoulage impeccable même sans matière grasse, passage au lave-vaisselle, four, congélateur et micro-ondes.</p>",
    desc_en: "<p>Perfect your cakes with this certified food-grade silicone mold set of 6. Flawless release even without grease, dishwasher, oven, freezer and microwave safe.</p>",
    benefits_fr: ["6 moules inclus", "Sans BPA certifié", "Résistant four et congélateur", "Démoulage parfait", "Lave-vaisselle safe"],
    benefits_en: ["6 molds included", "BPA-free certified", "Oven and freezer safe", "Perfect release", "Dishwasher safe"],
    args_fr: ["Viral TikTok pâtisserie", "Cadeau idéal femme/maman", "Remplace moules métal"],
    args_en: ["TikTok baking viral", "Perfect gift for bakers", "Replaces metal molds"],
    tags: ["moule", "silicone", "pâtisserie", "cuisine"], trendScore: 70, keywords: ["moule", "mold", "pâtisserie", "baking", "cuisine", "kitchen", "gâteau", "cake"],
  },

  // ── sport-fitness ─────────────────────────────────────────────────────────────
  {
    id: "sf-01", name_fr: "Pistolet Massage Musculaire 30 Vitesses 3200RPM", name_en: "Muscle Massage Gun 30 Speeds 3200RPM",
    categorySlug: "sport-fitness", price: 54.99, cost: 13.00, photoKeyword: "percussion massage gun muscle recovery athlete",
    short_fr: "Pistolet massage professionnel 30 vitesses, 6 têtes, autonomie 8h, ultrasilencieux 40dB.",
    short_en: "Professional massage gun 30 speeds, 6 heads, 8h battery, ultra-quiet 40dB.",
    desc_fr: "<p>Récupérez 3x plus vite après l'effort avec ce pistolet massage 3200RPM. 30 niveaux d'intensité, 6 têtes interchangeables pour chaque groupe musculaire. Ultrasilencieux 40dB — utilisable partout.</p>",
    desc_en: "<p>Recover 3x faster after exercise with this 3200RPM massage gun. 30 intensity levels, 6 interchangeable heads for every muscle group. Ultra-quiet 40dB — usable anywhere.</p>",
    benefits_fr: ["30 vitesses réglables", "6 têtes interchangeables", "Autonomie 8 heures", "Ultrasilencieux 40dB", "Valise de transport incluse"],
    benefits_en: ["30 adjustable speeds", "6 interchangeable heads", "8-hour battery", "Ultra-quiet 40dB", "Carry case included"],
    args_fr: ["Évite courbatures et blessures", "Viral TikTok fitness", "Utilisé par sportifs pro"],
    args_en: ["Prevents soreness and injuries", "TikTok fitness viral", "Used by pro athletes"],
    tags: ["massage", "sport", "récupération", "muscles"], trendScore: 92, keywords: ["massage", "musculaire", "muscle", "sport", "fitness", "récupération", "recovery"],
  },
  {
    id: "sf-02", name_fr: "Tapis Yoga Antidérapant Premium 6mm", name_en: "Premium Non-Slip Yoga Mat 6mm",
    categorySlug: "sport-fitness", price: 34.99, cost: 8.00, photoKeyword: "premium non-slip yoga mat exercise",
    short_fr: "Tapis yoga 6mm, matière TPE écologique, antidérapant double face, sangle transport.",
    short_en: "6mm yoga mat, eco-friendly TPE, double-sided non-slip, carrying strap.",
    desc_fr: "<p>Pratiquez le yoga et le pilates dans les meilleures conditions avec ce tapis premium en TPE écologique. 6mm d'épaisseur pour protéger vos articulations, surface antidérapante double face.</p>",
    desc_en: "<p>Practice yoga and Pilates in the best conditions with this eco-friendly TPE premium mat. 6mm thickness to protect your joints, double-sided non-slip surface.</p>",
    benefits_fr: ["TPE écologique sans PVC", "6mm protection articulations", "Antidérapant double face", "Sangle transport incluse", "183 x 61cm large"],
    benefits_en: ["Eco-friendly TPE no PVC", "6mm joint protection", "Double-sided non-slip", "Carrying strap included", "183 x 61cm large size"],
    args_fr: ["Yoga maison en hausse post-COVID", "Cadeau idéal sportif", "Marché fitness croissant"],
    args_en: ["Home yoga growing trend", "Perfect fitness gift", "Growing fitness market"],
    tags: ["yoga", "tapis", "sport", "fitness"], trendScore: 78, keywords: ["yoga", "tapis", "mat", "sport", "fitness", "pilates", "stretching"],
  },
  {
    id: "sf-03", name_fr: "Corde à Sauter Numérique Compteur Calories", name_en: "Digital Jump Rope Calorie Counter",
    categorySlug: "sport-fitness", price: 22.99, cost: 5.00, photoKeyword: "digital jump rope counter calories fitness",
    short_fr: "Corde à sauter digitale avec écran LCD, compteur sauts/calories/temps, câble acier.",
    short_en: "Digital jump rope with LCD screen, jump/calorie/time counter, steel cable.",
    desc_fr: "<p>Brûlez 1000 calories par heure avec cette corde à sauter intelligente. Écran LCD affichant sauts, calories brûlées et temps de séance. Câble acier PVC pour durabilité, poignées antidérapantes.</p>",
    desc_en: "<p>Burn 1000 calories per hour with this smart jump rope. LCD screen showing jumps, calories burned, and session time. PVC steel cable for durability, anti-slip handles.</p>",
    benefits_fr: ["Écran LCD sauts/calories/temps", "Câble acier inoxydable", "Poignées ergonomiques", "Longueur ajustable", "Cardio efficace maison"],
    benefits_en: ["LCD jump/calorie/time screen", "Stainless steel cable", "Ergonomic handles", "Adjustable length", "Effective home cardio"],
    args_fr: ["Sport maison sans matériel lourd", "Viral boxeurs et fitness", "Prix abordable"],
    args_en: ["Home sport without heavy equipment", "Viral with boxers and fitness", "Affordable price"],
    tags: ["corde", "sauter", "cardio", "sport"], trendScore: 73, keywords: ["corde", "jump rope", "cardio", "sport", "fitness", "sauter"],
  },
  {
    id: "sf-04", name_fr: "Bandes Élastiques Résistance Set 5 Niveaux", name_en: "Resistance Bands Set 5 Levels",
    categorySlug: "sport-fitness", price: 19.99, cost: 4.00, photoKeyword: "resistance bands set exercise home fitness",
    short_fr: "Set 5 bandes élastiques de résistance 10-50kg, latex naturel, poignées et sac inclus.",
    short_en: "Set of 5 resistance bands 10-50kg, natural latex, handles and bag included.",
    desc_fr: "<p>Entraînez-vous efficacement partout avec ce set de 5 bandes élastiques. Latex naturel premium, résistances de 10 à 50kg (combinables), poignées confortables, cheville et ancre de porte incluses.</p>",
    desc_en: "<p>Train effectively anywhere with this set of 5 resistance bands. Premium natural latex, resistances from 10 to 50kg (combinable), comfortable handles, ankle and door anchor included.</p>",
    benefits_fr: ["5 niveaux de résistance", "Latex naturel premium", "Poignées + ancre porte incluses", "Remplace salle de sport", "Sac transport fourni"],
    benefits_en: ["5 resistance levels", "Premium natural latex", "Handles + door anchor", "Replaces gym", "Carrying bag included"],
    args_fr: ["Sport maison tendance", "Voyage et bureau compatibles", "Pas cher et efficace"],
    args_en: ["Home workout trend", "Travel and office friendly", "Cheap and effective"],
    tags: ["élastiques", "résistance", "sport", "fitness"], trendScore: 76, keywords: ["élastiques", "resistance", "bands", "sport", "fitness", "gym", "muscu"],
  },
  {
    id: "sf-05", name_fr: "Foam Roller Massage Récupération 33cm Vibrant", name_en: "33cm Vibrating Foam Roller Massage Recovery",
    categorySlug: "sport-fitness", price: 44.99, cost: 11.00, photoKeyword: "vibrating foam roller massage recovery sports",
    short_fr: "Foam roller vibrant 4 intensités, dénoue nœuds musculaires, rechargeable USB.",
    short_en: "Vibrating foam roller 4 intensities, relieves muscle knots, USB rechargeable.",
    desc_fr: "<p>Soulagez douleurs musculaires et tensions avec ce foam roller vibrant 4 niveaux. La vibration pénètre 3x plus profond qu'un rouleau classique. Parfait avant et après l'effort.</p>",
    desc_en: "<p>Relieve muscle pain and tension with this 4-level vibrating foam roller. Vibration penetrates 3x deeper than a regular roller. Perfect before and after exercise.</p>",
    benefits_fr: ["4 niveaux vibration", "3x plus efficace classique", "Rechargeable USB-C", "Haute densité EPP", "Idéal récupération sportive"],
    benefits_en: ["4 vibration levels", "3x more effective than standard", "USB-C rechargeable", "High-density EPP", "Ideal sports recovery"],
    args_fr: ["Kinés l'utilisent en cabinet", "Évite blessures surentraînement", "Cadeau sportif premium"],
    args_en: ["Physios use it in practice", "Prevents overtraining injuries", "Premium sports gift"],
    tags: ["foam", "roller", "massage", "récupération"], trendScore: 81, keywords: ["foam roller", "roller", "massage", "récupération", "recovery", "sport", "kiné"],
  },
  {
    id: "sf-06", name_fr: "Gants de Musculation Antidérapants avec Poignets", name_en: "Non-Slip Weightlifting Gloves with Wrist Wraps",
    categorySlug: "sport-fitness", price: 17.99, cost: 3.50, photoKeyword: "weightlifting gloves wrist support gym",
    short_fr: "Gants musculation avec soutien poignet intégré, antidérapant, demi-doigts, taille S-XXL.",
    short_en: "Weightlifting gloves with wrist support, non-slip, half-finger, S-XXL.",
    desc_fr: "<p>Améliorez vos performances et protégez vos mains pendant la musculation. Cuir synthétique résistant, gel intégré anti-ampoules, velcro soutien poignet réglable.</p>",
    desc_en: "<p>Improve performance and protect your hands during weightlifting. Durable synthetic leather, anti-blister gel padding, adjustable velcro wrist support.</p>",
    benefits_fr: ["Cuir synthétique durable", "Gel anti-ampoules intégré", "Soutien poignet réglable", "Demi-doigts confortables", "Tailles S à XXL"],
    benefits_en: ["Durable synthetic leather", "Anti-blister gel padding", "Adjustable wrist support", "Comfortable half-finger", "Sizes S to XXL"],
    args_fr: ["Indispensable salle de sport", "Évite ampoules et blessures", "Cadeau sportif abordable"],
    args_en: ["Essential gym accessory", "Prevents blisters and injuries", "Affordable sports gift"],
    tags: ["gants", "musculation", "sport", "poignet"], trendScore: 69, keywords: ["gants", "gloves", "musculation", "gym", "sport", "fitness"],
  },

  // ── beaute-soin ───────────────────────────────────────────────────────────────
  {
    id: "bs-01", name_fr: "Nettoyant Visage Électrique Silicone Ultrason", name_en: "Ultrasonic Electric Silicone Face Cleanser",
    categorySlug: "beaute-soin", price: 29.99, cost: 6.50, photoKeyword: "electric silicone face cleanser brush skin care",
    short_fr: "Brosse nettoyante visage silicone, ultrason 7000 vibrations/min, étanche, 3 modes.",
    short_en: "Silicone face cleansing brush, 7000 vibrations/min ultrasonic, waterproof, 3 modes.",
    desc_fr: "<p>Purifiez votre peau en profondeur avec cette brosse nettoyante silicone à ultrasons. 7000 vibrations/min éliminent 99,5% des impuretés. 3 modes (nettoyage, massage, soin), 100% étanche.</p>",
    desc_en: "<p>Deep cleanse your skin with this ultrasonic silicone cleansing brush. 7000 vibrations/min removes 99.5% of impurities. 3 modes (cleansing, massage, care), 100% waterproof.</p>",
    benefits_fr: ["7000 vibrations/min ultrason", "Élimine 99,5% impuretés", "3 modes personnalisés", "100% étanche", "Rechargeable USB"],
    benefits_en: ["7000 vibrations/min ultrasonic", "Removes 99.5% impurities", "3 custom modes", "100% waterproof", "USB rechargeable"],
    args_fr: ["Viral TikTok skincare", "Remplace exfoliant manuel", "Peaux sensibles compatibles"],
    args_en: ["TikTok skincare viral", "Replaces manual exfoliants", "Sensitive skin compatible"],
    tags: ["nettoyant", "visage", "beauté", "soin"], trendScore: 86, keywords: ["nettoyant", "cleanser", "visage", "face", "beauté", "beauty", "soin", "skin"],
  },
  {
    id: "bs-02", name_fr: "Masque LED Visage 7 Couleurs Photothérapie", name_en: "7-Color LED Face Mask Phototherapy",
    categorySlug: "beaute-soin", price: 49.99, cost: 12.00, photoKeyword: "led face mask phototherapy red light anti aging",
    short_fr: "Masque LED 7 couleurs anti-âge, luminothérapie, réduit acné et rides, 20 min/jour.",
    short_en: "7-color LED anti-aging mask, light therapy, reduces acne and wrinkles, 20 min/day.",
    desc_fr: "<p>Rajeunissez votre peau sans chirurgie avec ce masque LED 7 couleurs. Lumière rouge (anti-âge), bleue (anti-acné), verte (éclat), infrarouge (collagène)... 20 minutes par jour suffisent.</p>",
    desc_en: "<p>Rejuvenate your skin without surgery with this 7-color LED mask. Red light (anti-aging), blue (anti-acne), green (radiance), infrared (collagen)... 20 minutes per day is all it takes.</p>",
    benefits_fr: ["7 longueurs d'onde thérapeutiques", "Stimule production collagène", "Réduit acné et rides", "20 min par session", "Résultats visibles 4 semaines"],
    benefits_en: ["7 therapeutic wavelengths", "Stimulates collagen production", "Reduces acne and wrinkles", "20 min per session", "Visible results in 4 weeks"],
    args_fr: ["Traitement clinique à domicile", "Viral TikTok beauté", "Dermatos le recommandent"],
    args_en: ["Clinical treatment at home", "TikTok beauty viral", "Dermatologists recommend"],
    tags: ["masque", "LED", "anti-âge", "beauté"], trendScore: 89, keywords: ["masque", "mask", "LED", "anti-âge", "anti-aging", "beauté", "beauty", "photothérapie"],
  },
  {
    id: "bs-03", name_fr: "Sèche-Cheveux Ionique 2200W Diffuseur Inclus", name_en: "2200W Ionic Hair Dryer with Diffuser",
    categorySlug: "beaute-soin", price: 44.99, cost: 11.00, photoKeyword: "ionic hair dryer professional 2200w diffuser",
    short_fr: "Sèche-cheveux ionique professionnel 2200W, 3 températures, 2 vitesses, diffuseur inclus.",
    short_en: "Professional ionic hair dryer 2200W, 3 temperatures, 2 speeds, diffuser included.",
    desc_fr: "<p>Obtenez un brushing professionnel chez vous avec ce sèche-cheveux ionique 2200W. La technologie ionique élimine les frisottis et apporte brillance. Diffuseur et concentrateur inclus.</p>",
    desc_en: "<p>Achieve a professional blow-dry at home with this 2200W ionic hair dryer. Ionic technology eliminates frizz and adds shine. Diffuser and concentrator included.</p>",
    benefits_fr: ["2200W séchage ultra-rapide", "Technologie ionique anti-frisottis", "3 températures + air froid", "Diffuseur et concentrateur", "Arrêt thermique sécurité"],
    benefits_en: ["2200W ultra-fast drying", "Ionic anti-frizz technology", "3 temperatures + cool air", "Diffuser and concentrator", "Thermal cutoff safety"],
    args_fr: ["Économie salon de coiffure", "Cheveux soyeux garantis", "Cadeau femme idéal"],
    args_en: ["Save on hair salon costs", "Silky hair guaranteed", "Perfect gift for women"],
    tags: ["sèche-cheveux", "cheveux", "ionique", "beauté"], trendScore: 77, keywords: ["sèche-cheveux", "hair dryer", "cheveux", "hair", "beauté", "beauty"],
  },
  {
    id: "bs-04", name_fr: "Masseur Visage Micro-Courant Lifting EMS", name_en: "EMS Micro-Current Face Lifting Massager",
    categorySlug: "beaute-soin", price: 39.99, cost: 9.50, photoKeyword: "ems microcurrent face lifting massager beauty",
    short_fr: "Masseur visage EMS micro-courant, lifting sans chirurgie, photon LED, rechargeable.",
    short_en: "EMS micro-current face massager, non-surgical lifting, LED photon, rechargeable.",
    desc_fr: "<p>Retrouvez un visage lifté et tonifié avec ce masseur EMS. Le micro-courant stimule les muscles faciaux et raffermit la peau, effaçant rides et poches. Compatible gel conducteur.</p>",
    desc_en: "<p>Restore a lifted and toned face with this EMS massager. Micro-current stimulates facial muscles and firms skin, erasing wrinkles and bags. Compatible with conductive gel.</p>",
    benefits_fr: ["EMS micro-courant lifting", "Photon LED anti-âge", "Rechargeable USB", "Visible en 2 semaines", "Cliniquement testé"],
    benefits_en: ["EMS micro-current lifting", "Anti-aging LED photon", "USB rechargeable", "Visible in 2 weeks", "Clinically tested"],
    args_fr: ["Alternative naturelle chirurgie", "Viral TikTok anti-âge", "Cliniques l'utilisent"],
    args_en: ["Natural surgery alternative", "TikTok anti-aging viral", "Used in clinics"],
    tags: ["masseur", "lifting", "visage", "EMS"], trendScore: 83, keywords: ["lifting", "masseur", "EMS", "visage", "face", "anti-âge", "beauté", "beauty"],
  },
  {
    id: "bs-05", name_fr: "Épilateur Électrique Corps Visage Étanche IPX6", name_en: "IPX6 Waterproof Electric Epilator Face Body",
    categorySlug: "beaute-soin", price: 34.99, cost: 8.00, photoKeyword: "electric epilator waterproof body face hair removal",
    short_fr: "Épilateur électrique 40 pinces, étanche douche, rasoir et peeling inclus, silencieux.",
    short_en: "Electric epilator 40 tweezers, shower-proof, shaver and peeling included, quiet.",
    desc_fr: "<p>Épilation durable et douce avec cet épilateur 40 pinces IPX6. Utilisable sous la douche, silencieux 50dB, tête rasoir et peeling incluses pour une épilation complète corps et visage.</p>",
    desc_en: "<p>Long-lasting, gentle hair removal with this 40-tweezer IPX6 epilator. Shower-safe, quiet 50dB, shaver and peeling heads included for complete body and face epilation.</p>",
    benefits_fr: ["40 pinces haute précision", "IPX6 utilisable douche", "Silencieux 50dB", "Rasoir + peeling inclus", "Rechargeable USB"],
    benefits_en: ["40 high-precision tweezers", "IPX6 shower-safe", "Quiet 50dB", "Shaver + peeling included", "USB rechargeable"],
    args_fr: ["Économie épilation salon", "Résultat 4 semaines garanti", "Pour tout type de peau"],
    args_en: ["Save on salon waxing costs", "4-week results guaranteed", "All skin types"],
    tags: ["épilateur", "beauté", "épilation", "soin"], trendScore: 74, keywords: ["épilateur", "epilator", "épilation", "hair removal", "beauté", "beauty"],
  },

  // ── tech-gadgets ─────────────────────────────────────────────────────────────
  {
    id: "tg-01", name_fr: "Écouteurs Sans Fil Bluetooth ANC 40H Autonomie", name_en: "Wireless Bluetooth ANC Earbuds 40H Battery",
    categorySlug: "tech-gadgets", price: 59.99, cost: 14.00, photoKeyword: "wireless earbuds anc noise cancelling bluetooth",
    short_fr: "Écouteurs TWS ANC, réduction bruit active, 40h avec boîtier, son Hi-Fi, IPX5.",
    short_en: "TWS ANC earbuds, active noise cancelling, 40h with case, Hi-Fi sound, IPX5.",
    desc_fr: "<p>Immergez-vous dans votre musique sans distractions avec ces écouteurs ANC. Réduction de bruit active jusqu'à -35dB, son Hi-Fi avec basses profondes, 40h d'autonomie totale. IPX5 résistant à l'eau.</p>",
    desc_en: "<p>Immerse yourself in music without distractions with these ANC earbuds. Active noise cancellation up to -35dB, Hi-Fi sound with deep bass, 40h total battery life. IPX5 water-resistant.</p>",
    benefits_fr: ["ANC -35dB bruit annulé", "40h autonomie totale", "Son Hi-Fi basses profondes", "IPX5 résistant eau", "Commandes tactiles"],
    benefits_en: ["ANC -35dB noise cancelled", "40h total battery", "Hi-Fi deep bass sound", "IPX5 water resistant", "Touch controls"],
    args_fr: ["Alternative AirPods Pro -60%", "Viral TikTok tech 2026", "Commandes vocales intégrées"],
    args_en: ["AirPods Pro alternative -60%", "TikTok tech viral 2026", "Built-in voice commands"],
    tags: ["écouteurs", "bluetooth", "ANC", "musique"], trendScore: 93, keywords: ["écouteurs", "earbuds", "bluetooth", "ANC", "musique", "music", "son", "audio"],
  },
  {
    id: "tg-02", name_fr: "Enceinte Bluetooth Portable Waterproof 360° 20W", name_en: "20W Waterproof 360° Portable Bluetooth Speaker",
    categorySlug: "tech-gadgets", price: 49.99, cost: 12.00, photoKeyword: "portable bluetooth speaker waterproof outdoor 360",
    short_fr: "Enceinte 360° 20W IPX7, autonomie 24h, basses profondes, lumières LED, filtre antibuée.",
    short_en: "360° 20W IPX7 speaker, 24h battery, deep bass, LED lights, anti-fog filter.",
    desc_fr: "<p>La sono portable parfaite pour plage, piscine, montagne et camping. IPX7 immergeable 30 min, son 360° 20W avec basses TrueBase, 24h d'autonomie, lumières LED ambiance.</p>",
    desc_en: "<p>The perfect portable speaker for beach, pool, mountain, and camping. IPX7 submersible 30 min, 360° 20W TrueBase sound, 24h battery, LED ambiance lights.</p>",
    benefits_fr: ["IPX7 immergeable 30 min", "Son 360° 20W TrueBase", "24h autonomie", "Lumières LED ambiance", "Appel mains-libres"],
    benefits_en: ["IPX7 submersible 30 min", "360° 20W TrueBase sound", "24h battery", "LED ambiance lights", "Hands-free calls"],
    args_fr: ["Indispensable été 2026", "Compatible iPhone & Android", "Cadeau tech bestseller"],
    args_en: ["Essential summer 2026", "iPhone & Android compatible", "Top tech gift"],
    tags: ["enceinte", "bluetooth", "musique", "portable"], trendScore: 87, keywords: ["enceinte", "speaker", "bluetooth", "musique", "music", "portable", "waterproof"],
  },
  {
    id: "tg-03", name_fr: "Powerbank 20000mAh Charge Rapide USB-C 65W", name_en: "20000mAh Fast Charge USB-C 65W Power Bank",
    categorySlug: "tech-gadgets", price: 44.99, cost: 10.50, photoKeyword: "power bank 20000mah fast charge usb-c portable",
    short_fr: "Batterie externe 20000mAh, charge rapide 65W USB-C, recharge laptop, 4 ports simultanés.",
    short_en: "20000mAh power bank, 65W USB-C fast charge, laptop charging, 4 simultaneous ports.",
    desc_fr: "<p>Ne tombez plus jamais en panne de batterie avec ce powerbank 20000mAh. Charge rapide 65W USB-C compatible MacBook et laptop, recharge 4 appareils simultanément. Indicateur LED précis.</p>",
    desc_en: "<p>Never run out of battery with this 20000mAh power bank. 65W USB-C fast charge compatible with MacBook and laptops, charges 4 devices simultaneously. Precise LED indicator.</p>",
    benefits_fr: ["20000mAh grande capacité", "65W USB-C charge laptop", "4 ports simultanés", "Affichage LED précis", "Charge 5x iPhone"],
    benefits_en: ["20000mAh large capacity", "65W USB-C laptop charging", "4 simultaneous ports", "Precise LED display", "Charges iPhone 5x"],
    args_fr: ["Voyageurs et télétravailleurs", "Recharge MacBook et Switch", "Indispensable en déplacement"],
    args_en: ["Travelers and remote workers", "Charges MacBook and Switch", "Essential on the go"],
    tags: ["batterie", "powerbank", "charge", "portable"], trendScore: 84, keywords: ["batterie", "powerbank", "power bank", "charge", "charging", "portable", "laptop"],
  },
  {
    id: "tg-04", name_fr: "Webcam Full HD 1080P Microphone Annulation Bruit", name_en: "Full HD 1080P Webcam with Noise-Cancelling Mic",
    categorySlug: "tech-gadgets", price: 34.99, cost: 8.00, photoKeyword: "full hd webcam 1080p microphone streaming",
    short_fr: "Webcam 1080P 60fps, microphone anti-bruit, autofocus, compatible Zoom/Teams/Stream.",
    short_en: "1080P 60fps webcam, noise-cancelling microphone, autofocus, Zoom/Teams/Stream.",
    desc_fr: "<p>Participez à vos réunions et streamez en qualité professionnelle avec cette webcam 1080P 60fps. Autofocus rapide, microphone stéréo anti-bruit, correction automatique de la lumière.</p>",
    desc_en: "<p>Join meetings and stream in professional quality with this 1080P 60fps webcam. Fast autofocus, stereo noise-cancelling microphone, automatic light correction.</p>",
    benefits_fr: ["1080P 60fps ultra-fluide", "Autofocus rapide précis", "Micro stéréo anti-bruit", "Correction lumière auto", "Plug & Play sans driver"],
    benefits_en: ["1080P 60fps ultra-smooth", "Fast precise autofocus", "Stereo noise-cancelling mic", "Auto light correction", "Plug & Play no driver"],
    args_fr: ["Télétravail et streaming", "Remplace webcam laptop basique", "Compatible toutes plateformes"],
    args_en: ["Remote work and streaming", "Replaces basic laptop webcam", "All platforms compatible"],
    tags: ["webcam", "streaming", "télétravail", "HD"], trendScore: 80, keywords: ["webcam", "streaming", "télétravail", "remote work", "zoom", "teams"],
  },
  {
    id: "tg-05", name_fr: "Hub USB-C 9-en-1 4K HDMI Ethernet SD", name_en: "9-in-1 USB-C Hub 4K HDMI Ethernet SD",
    categorySlug: "tech-gadgets", price: 39.99, cost: 9.50, photoKeyword: "usb-c hub 9 in 1 hdmi ethernet laptop",
    short_fr: "Hub USB-C 9 ports : 4K HDMI, Ethernet, SD, micro-SD, USB 3.0 x3, charge 100W pass-through.",
    short_en: "9-port USB-C hub: 4K HDMI, Ethernet, SD, micro-SD, 3x USB 3.0, 100W pass-through charging.",
    desc_fr: "<p>Transformez votre laptop en workstation avec ce hub USB-C 9-en-1. Affichage 4K HDMI, Ethernet gigabit, lecteur SD/micro-SD, 3 ports USB 3.0, charge pass-through 100W. Compatible Mac et PC.</p>",
    desc_en: "<p>Transform your laptop into a workstation with this 9-in-1 USB-C hub. 4K HDMI display, gigabit Ethernet, SD/micro-SD reader, 3x USB 3.0, 100W pass-through charging. Mac and PC compatible.</p>",
    benefits_fr: ["4K HDMI écran externe", "Ethernet gigabit stable", "Lecteur SD + micro-SD", "3 ports USB 3.0", "Charge pass-through 100W"],
    benefits_en: ["4K HDMI external display", "Stable gigabit Ethernet", "SD + micro-SD reader", "3x USB 3.0 ports", "100W pass-through charging"],
    args_fr: ["Indispensable MacBook/laptop fin", "Télétravail bureau maison", "Remplace docking station"],
    args_en: ["Essential for thin MacBook/laptop", "Home office remote work", "Replaces docking station"],
    tags: ["hub", "USB-C", "HDMI", "laptop"], trendScore: 83, keywords: ["hub", "USB-C", "HDMI", "laptop", "télétravail", "remote work"],
  },
  {
    id: "tg-06", name_fr: "Chargeur Sans Fil 3-en-1 iPhone Watch AirPods", name_en: "3-in-1 Wireless Charger iPhone Watch AirPods",
    categorySlug: "tech-gadgets", price: 34.99, cost: 8.00, photoKeyword: "3 in 1 wireless charger iphone apple watch airpods",
    short_fr: "Station charge sans fil 3-en-1, iPhone + Apple Watch + AirPods simultanément.",
    short_en: "3-in-1 wireless charging station, iPhone + Apple Watch + AirPods simultaneously.",
    desc_fr: "<p>Chargez tous vos appareils Apple simultanément avec cette station 3-en-1. Compatible iPhone 8 à 15 Pro Max, Apple Watch toutes séries, AirPods Pro/3. Charge rapide MagSafe 15W.</p>",
    desc_en: "<p>Charge all your Apple devices simultaneously with this 3-in-1 station. Compatible with iPhone 8 to 15 Pro Max, all Apple Watch series, AirPods Pro/3. 15W MagSafe fast charging.</p>",
    benefits_fr: ["Charge 3 appareils simultanément", "MagSafe 15W charge rapide", "Câble rangé propre", "Compatible toute la gamme Apple", "LED indicateur"],
    benefits_en: ["Charges 3 devices at once", "15W MagSafe fast charge", "Clean cable management", "Full Apple lineup compatible", "LED indicator"],
    args_fr: ["100M d'utilisateurs iPhone FR", "Cadeau Apple user parfait", "Bestseller Amazon UK/US"],
    args_en: ["100M iPhone users globally", "Perfect Apple user gift", "Amazon UK/US bestseller"],
    tags: ["chargeur", "sans-fil", "iPhone", "Apple"], trendScore: 88, keywords: ["chargeur", "charger", "sans-fil", "wireless", "iPhone", "Apple", "Watch", "AirPods"],
  },

  // ── bureau-productivite ───────────────────────────────────────────────────────
  {
    id: "bp-01", name_fr: "Lampe Bureau LED Sans Fil Rechargeable Tactile", name_en: "Wireless Rechargeable Touch LED Desk Lamp",
    categorySlug: "bureau-productivite", price: 32.99, cost: 7.50, photoKeyword: "led desk lamp wireless rechargeable touch dimmer",
    short_fr: "Lampe bureau LED sans fil, tactile 3 températures, 5 niveaux luminosité, autonomie 8h.",
    short_en: "Wireless LED desk lamp, touch 3 color temps, 5 brightness levels, 8h battery.",
    desc_fr: "<p>Éclairez votre bureau avec cette lampe LED sans fil rechargeable. Contrôle tactile, 3 températures de couleur (blanc chaud/neutre/froid), 5 niveaux de luminosité, autonomie 8h. Port USB-A intégré pour charger smartphone.</p>",
    desc_en: "<p>Light your desk with this wireless rechargeable LED lamp. Touch control, 3 color temperatures (warm/neutral/cool white), 5 brightness levels, 8h battery. Built-in USB-A port to charge your smartphone.</p>",
    benefits_fr: ["Sans fil — posée partout", "8h autonomie recharge USB", "3 températures + 5 niveaux", "Port charge USB intégré", "Design épuré minimaliste"],
    benefits_en: ["Wireless — place anywhere", "8h battery, USB recharge", "3 temps + 5 levels", "Built-in USB charging port", "Minimal clean design"],
    args_fr: ["Télétravail en hausse", "Protège les yeux (sans UV)", "Idéal chambre d'enfant aussi"],
    args_en: ["Remote work growing", "Eye protection (UV-free)", "Great for kids rooms too"],
    tags: ["lampe", "bureau", "LED", "sans-fil"], trendScore: 81, keywords: ["lampe", "lamp", "bureau", "desk", "LED", "sans-fil", "wireless", "lumière", "light"],
  },
  {
    id: "bp-02", name_fr: "Support Ordinateur Portable Réglable Ergonomique", name_en: "Adjustable Ergonomic Laptop Stand",
    categorySlug: "bureau-productivite", price: 27.99, cost: 6.00, photoKeyword: "ergonomic laptop stand adjustable aluminum",
    short_fr: "Support PC portable aluminium, 6 hauteurs réglables, pliable, antidérapant, universel.",
    short_en: "Aluminum laptop stand, 6 adjustable heights, foldable, anti-slip, universal.",
    desc_fr: "<p>Améliorez votre posture et réduisez douleurs cervicales avec ce support laptop aluminium. 6 niveaux de hauteur réglables, stable et antidérapant, compatible 10 à 17 pouces. Pliable pour transport.</p>",
    desc_en: "<p>Improve your posture and reduce neck pain with this aluminum laptop stand. 6 adjustable height levels, stable and anti-slip, compatible 10 to 17 inches. Foldable for travel.</p>",
    benefits_fr: ["Aluminium léger et solide", "6 hauteurs réglables", "Pliable pour transport", "Compatible 10-17 pouces", "Antidérapant stable"],
    benefits_en: ["Light and solid aluminum", "6 adjustable heights", "Foldable for travel", "10-17 inch compatible", "Anti-slip stable"],
    args_fr: ["Télétravail ergonomique", "Évite mal de dos/cou", "Compatible Mac et PC"],
    args_en: ["Ergonomic remote work", "Prevents back/neck pain", "Mac and PC compatible"],
    tags: ["support", "laptop", "ergonomique", "bureau"], trendScore: 78, keywords: ["support", "stand", "laptop", "bureau", "desk", "ergonomique", "télétravail"],
  },
  {
    id: "bp-03", name_fr: "Organisateur Bureau Rotatif 360° Bambou", name_en: "360° Rotating Bamboo Desk Organizer",
    categorySlug: "bureau-productivite", price: 24.99, cost: 5.50, photoKeyword: "rotating bamboo desk organizer office storage",
    short_fr: "Organisateur bureau bambou 360°, 4 compartiments rotatifs, stylos/téléphone/papiers.",
    short_en: "360° rotating bamboo desk organizer, 4 rotating compartments, pens/phone/papers.",
    desc_fr: "<p>Gardez votre bureau impeccable avec cet organisateur bambou rotatif 360°. 4 compartiments rotatifs pour stylos, téléphone, papiers et accessoires. Matière naturelle et élégante.</p>",
    desc_en: "<p>Keep your desk immaculate with this 360° rotating bamboo organizer. 4 rotating compartments for pens, phone, papers, and accessories. Natural and elegant material.</p>",
    benefits_fr: ["Bambou naturel éco-responsable", "Rotation 360° pratique", "4 compartiments modulables", "Stable et antidérapant", "Design zen minimaliste"],
    benefits_en: ["Natural eco-friendly bamboo", "Convenient 360° rotation", "4 modular compartments", "Stable and anti-slip", "Zen minimalist design"],
    args_fr: ["Tendance bureau zen 2026", "Cadeau collègue parfait", "Compatible home office"],
    args_en: ["2026 zen desk trend", "Perfect colleague gift", "Home office compatible"],
    tags: ["organisateur", "bureau", "bambou", "rangement"], trendScore: 71, keywords: ["organisateur", "organizer", "bureau", "desk", "rangement", "storage", "bambou"],
  },
  {
    id: "bp-04", name_fr: "Repose-Poignets Clavier Souris Mémoire Forme", name_en: "Memory Foam Keyboard Mouse Wrist Rest Set",
    categorySlug: "bureau-productivite", price: 19.99, cost: 4.00, photoKeyword: "memory foam wrist rest keyboard mouse office",
    short_fr: "Set repose-poignets clavier + souris mousse à mémoire de forme, revêtement tissu doux.",
    short_en: "Keyboard + mouse wrist rest set, memory foam, soft fabric cover.",
    desc_fr: "<p>Prévenez le syndrome du canal carpien avec ce set repose-poignets en mousse mémoire de forme. Support ergonomique optimal, revêtement tissu respirant lavable, antidérapant. Inclus pour clavier et souris.</p>",
    desc_en: "<p>Prevent carpal tunnel syndrome with this memory foam wrist rest set. Optimal ergonomic support, washable breathable fabric cover, anti-slip. Included for keyboard and mouse.</p>",
    benefits_fr: ["Mousse mémoire de forme", "Prévient syndrome carpien", "Tissu respirant lavable", "Set clavier + souris", "Antidérapant stable"],
    benefits_en: ["Memory foam material", "Prevents carpal tunnel", "Washable breathable fabric", "Keyboard + mouse set", "Anti-slip stable"],
    args_fr: ["Télétravail 8h+/jour", "Médecins le recommandent", "Prix imbattable"],
    args_en: ["8h+/day remote work", "Doctors recommend it", "Unbeatable price"],
    tags: ["repose-poignet", "ergonomique", "bureau", "clavier"], trendScore: 69, keywords: ["repose-poignet", "wrist rest", "ergonomique", "bureau", "desk", "clavier", "keyboard"],
  },
  {
    id: "bp-05", name_fr: "Tableau Blanc Magnétique Effaçable 60x90cm", name_en: "60x90cm Magnetic Dry-Erase Whiteboard",
    categorySlug: "bureau-productivite", price: 29.99, cost: 7.00, photoKeyword: "magnetic whiteboard dry erase office planning",
    short_fr: "Tableau blanc magnétique 60x90cm, effaçable à sec, avec kit marqueurs et aimants.",
    short_en: "60x90cm magnetic whiteboard, dry-erase, includes markers and magnets kit.",
    desc_fr: "<p>Organisez vos projets et brainstorm efficacement avec ce tableau blanc magnétique 60x90cm. Surface émaillée ultra-lisse, effaçage impeccable, fixation murale sans perçage incluse. Kit marqueurs + aimants offert.</p>",
    desc_en: "<p>Organize projects and brainstorm effectively with this 60x90cm magnetic whiteboard. Ultra-smooth enameled surface, perfect erasure, no-drill wall mounting included. Markers + magnets kit included.</p>",
    benefits_fr: ["Surface émaillée ultra-lisse", "Magnétique double usage", "Fixation sans perçage", "Kit marqueurs + aimants", "60x90cm grand format"],
    benefits_en: ["Ultra-smooth enameled surface", "Dual magnetic use", "No-drill wall mounting", "Markers + magnets kit", "Large 60x90cm format"],
    args_fr: ["Home office et PME", "Réunions et brainstorm", "Cadeau manager idéal"],
    args_en: ["Home office and SMEs", "Meetings and brainstorming", "Perfect manager gift"],
    tags: ["tableau", "blanc", "bureau", "organisation"], trendScore: 67, keywords: ["tableau", "whiteboard", "bureau", "office", "organisation", "planning"],
  },

  // ── enfant-famille ────────────────────────────────────────────────────────────
  {
    id: "ef-01", name_fr: "Veilleuse Bébé Musicale Projecteur Étoiles", name_en: "Musical Baby Night Light Star Projector",
    categorySlug: "enfant-famille", price: 27.99, cost: 6.00, photoKeyword: "baby night light star projector musical nursery",
    short_fr: "Veilleuse bébé projecteur d'étoiles 360°, 12 mélodies, minuterie, télécommande.",
    short_en: "Baby star projector night light 360°, 12 melodies, timer, remote control.",
    desc_fr: "<p>Endormez bébé en douceur avec cette veilleuse musicale projecteur. 360° d'étoiles au plafond, 12 berceuses apaisantes, minuterie 20/40/60 minutes et télécommande pour ne pas déranger bébé.</p>",
    desc_en: "<p>Help baby fall asleep gently with this musical projector night light. 360° stars on the ceiling, 12 soothing lullabies, 20/40/60 min timer and remote control so you don't disturb baby.</p>",
    benefits_fr: ["Projecteur étoiles 360°", "12 mélodies berceuses", "Minuterie 20/40/60 min", "Télécommande incluse", "3 couleurs de lumière"],
    benefits_en: ["360° star projector", "12 lullaby melodies", "20/40/60 min timer", "Remote control included", "3 light colors"],
    args_fr: ["Cadeau naissance parfait", "Réduit pleurs nocturnes", "Pediatres l'approuvent"],
    args_en: ["Perfect birth gift", "Reduces night crying", "Pediatricians approve"],
    tags: ["bébé", "veilleuse", "musique", "enfant"], trendScore: 79, keywords: ["bébé", "baby", "veilleuse", "night light", "enfant", "famille", "family"],
  },
  {
    id: "ef-02", name_fr: "Babyphone Vidéo WiFi 5 Pouces Infrarouge", name_en: "5-Inch WiFi Video Baby Monitor Infrared",
    categorySlug: "enfant-famille", price: 89.99, cost: 22.00, photoKeyword: "video baby monitor wifi 5 inch infrared night",
    short_fr: "Babyphone vidéo 5 pouces, WiFi, vision nocturne IR, zoom 4x, interphone bidirectionnel.",
    short_en: "5-inch video baby monitor, WiFi, IR night vision, 4x zoom, two-way intercom.",
    desc_fr: "<p>Surveillez bébé en permanence avec ce babyphone vidéo 5 pouces haute résolution. Vision nocturne infrarouge automatique, connexion WiFi pour voir depuis smartphone, interphone bidirectionnel, température ambiante.</p>",
    desc_en: "<p>Monitor baby at all times with this high-resolution 5-inch video monitor. Automatic infrared night vision, WiFi connection to view from smartphone, two-way intercom, ambient temperature.</p>",
    benefits_fr: ["Écran 5 pouces HD", "Vision nocturne IR auto", "Contrôle depuis smartphone", "Interphone bidirectionnel", "Capteur température"],
    benefits_en: ["5-inch HD screen", "Auto IR night vision", "Smartphone remote view", "Two-way intercom", "Temperature sensor"],
    args_fr: ["Sécurité bébé première priorité", "Dormir tranquille parents", "Indispensable naissance"],
    args_en: ["Baby safety top priority", "Parents sleep peacefully", "Essential from birth"],
    tags: ["babyphone", "bébé", "vidéo", "surveillance"], trendScore: 82, keywords: ["babyphone", "baby monitor", "bébé", "baby", "surveillance", "vidéo"],
  },
  {
    id: "ef-03", name_fr: "Jeu Construction Magnétique 3D 120 Pièces", name_en: "120-Piece 3D Magnetic Building Set",
    categorySlug: "enfant-famille", price: 34.99, cost: 8.50, photoKeyword: "magnetic building blocks 3d kids construction toys",
    short_fr: "Set construction magnétique 120 pièces, STEM, 3-10 ans, formes géométriques colorées.",
    short_en: "120-piece magnetic building set, STEM, ages 3-10, colorful geometric shapes.",
    desc_fr: "<p>Stimulez la créativité et l'intelligence spatiale de votre enfant avec ces 120 pièces magnétiques colorées. Certifié EN71, sans BPA, magnets sécurisés pour enfants dès 3 ans. Développement STEM.</p>",
    desc_en: "<p>Stimulate your child's creativity and spatial intelligence with these 120 colorful magnetic pieces. EN71 certified, BPA-free, child-safe magnets for ages 3+. STEM development.</p>",
    benefits_fr: ["120 pièces colorées", "Certifié EN71 sécurisé", "Développement STEM", "Compatible 3-10 ans", "Stimule créativité"],
    benefits_en: ["120 colorful pieces", "EN71 safety certified", "STEM development", "Ages 3-10", "Stimulates creativity"],
    args_fr: ["Cadeau Noël/anniversaire viral", "Approuvé enseignants", "Heures de jeu garanties"],
    args_en: ["Viral Christmas/birthday gift", "Teacher-approved", "Hours of play guaranteed"],
    tags: ["jeu", "magnétique", "enfant", "construction"], trendScore: 80, keywords: ["jeu", "toy", "magnétique", "enfant", "kids", "construction", "STEM", "famille"],
  },
  {
    id: "ef-04", name_fr: "Sac à Langer Imperméable Multi-Compartiments", name_en: "Waterproof Multi-Compartment Diaper Bag",
    categorySlug: "enfant-famille", price: 39.99, cost: 9.00, photoKeyword: "diaper bag waterproof multi compartment baby",
    short_fr: "Sac à langer grand format 20L, imperméable, port USB, matelas à langer inclus.",
    short_en: "Large 20L diaper bag, waterproof, USB charging port, changing mat included.",
    desc_fr: "<p>Emportez tout le nécessaire bébé avec ce sac à langer 20L. Tissu imperméable Oxford, port USB pour recharger téléphone, 14 poches organisées, matelas à langer réflecteur inclus, bandoulière et poignées.</p>",
    desc_en: "<p>Carry everything baby needs with this 20L diaper bag. Waterproof Oxford fabric, USB port to charge your phone, 14 organized pockets, reflective changing mat included, shoulder strap and handles.</p>",
    benefits_fr: ["20L grande capacité", "Port USB charge téléphone", "14 poches organisées", "Matelas à langer inclus", "Tissu imperméable Oxford"],
    benefits_en: ["20L large capacity", "USB phone charging port", "14 organized pockets", "Changing mat included", "Waterproof Oxford fabric"],
    args_fr: ["Cadeau future maman parfait", "Unisexe papa/maman", "Design moderne non-babyish"],
    args_en: ["Perfect gift for new moms", "Unisex mom/dad", "Modern non-babyish design"],
    tags: ["sac", "langer", "bébé", "imperméable"], trendScore: 73, keywords: ["sac", "bag", "langer", "bébé", "baby", "famille", "family"],
  },
];

// Keyword → category mapping for trend matching
export const KEYWORD_CATEGORY_MAP: Record<string, string[]> = {
  "gadgets-voiture": ["voiture", "auto", "car", "driving", "conducteur", "drive", "road", "parking", "gps", "dashcam"],
  "maison-intelligente": ["maison", "home", "smart", "connecté", "connected", "alexa", "google home", "domotique", "aspirateur", "vacuum", "robot", "wifi"],
  "cuisine-pratique": ["cuisine", "kitchen", "cook", "food", "recette", "recipe", "friteuse", "fryer", "robot", "café", "coffee", "baking", "pâtisserie"],
  "sport-fitness": ["sport", "fitness", "gym", "muscle", "workout", "running", "yoga", "pilates", "massage", "récupération", "recovery", "healthy", "santé"],
  "beaute-soin": ["beauté", "beauty", "skin", "soin", "skincare", "visage", "face", "cheveux", "hair", "lifting", "anti-âge", "anti-aging", "makeup"],
  "tech-gadgets": ["tech", "gadget", "phone", "bluetooth", "écouteurs", "earbuds", "enceinte", "speaker", "chargeur", "charger", "laptop", "mac"],
  "bureau-productivite": ["bureau", "desk", "office", "work", "télétravail", "remote", "productivité", "productivity", "organisation", "planning"],
  "enfant-famille": ["enfant", "kids", "children", "famille", "family", "bébé", "baby", "jouet", "toy", "naissance", "birth"],
};

export function matchTrendToCategories(trends: string[]): string[] {
  const scores: Record<string, number> = {};
  for (const trend of trends) {
    const lowerTrend = trend.toLowerCase();
    for (const [category, keywords] of Object.entries(KEYWORD_CATEGORY_MAP)) {
      for (const kw of keywords) {
        if (lowerTrend.includes(kw)) {
          scores[category] = (scores[category] || 0) + 1;
        }
      }
    }
  }
  // Sort by score, fallback to all categories
  const sorted = Object.entries(scores).sort(([, a], [, b]) => b - a).map(([cat]) => cat);
  // Always include all categories (in shuffled order) as fallback
  const allCats = Object.keys(KEYWORD_CATEGORY_MAP);
  const remaining = allCats.filter(c => !sorted.includes(c));
  return [...sorted, ...remaining];
}
