export interface CatalogProduct {
  id: string;
  name_fr: string;
  name_en: string;
  categorySlug: string;
  price: number;
  cost: number;
  photoKeyword: string;
  short_fr: string;
  short_en: string;
  desc_fr: string;
  desc_en: string;
  benefits_fr: string[];
  benefits_en: string[];
  args_fr: string[];
  args_en: string[];
  tags: string[];
  trendScore: number;
  keywords: string[];
  supplierUrl?: string;
  amazonAsin?: string;
}

const TAG = "vellio42-21";
const amz = (asin: string) => `https://www.amazon.fr/dp/${asin}?tag=${TAG}`;

export const PRODUCT_CATALOG: CatalogProduct[] = [

  // ── tech-gadgets ─────────────────────────────────────────────────────────────
  {
    id: "tg-01",
    name_fr: "Anker Soundcore P40i — Écouteurs Sans Fil ANC",
    name_en: "Anker Soundcore P40i — Wireless Earbuds ANC",
    categorySlug: "tech-gadgets", price: 49.99, cost: 0,
    amazonAsin: "B0C7MFKW54",
    supplierUrl: amz("B0C7MFKW54"),
    photoKeyword: "anker soundcore p40i wireless earbuds anc",
    short_fr: "Réduction de bruit active, 60h d'autonomie, son Hi-Res certifié.",
    short_en: "Active noise cancelling, 60h battery, Hi-Res certified audio.",
    desc_fr: "<p>Les Soundcore P40i offrent une réduction de bruit active adaptative qui s'ajuste automatiquement à votre environnement. Son Hi-Res certifié avec des drivers 11mm et 60 heures d'autonomie totale.</p><p>Idéal pour le travail, les transports et le sport.</p>",
    desc_en: "<p>Soundcore P40i feature adaptive active noise cancelling that automatically adjusts to your environment. Hi-Res certified audio with 11mm drivers and 60 hours total battery life.</p>",
    benefits_fr: ["ANC adaptatif multi-mode", "60h autonomie totale", "Son Hi-Res certifié", "Charge rapide 10min → 4h", "Résistance IPX5"],
    benefits_en: ["Adaptive multi-mode ANC", "60h total battery", "Hi-Res certified", "10min charge → 4h", "IPX5 water resistance"],
    args_fr: ["Meilleur rapport qualité/prix ANC", "Marque Anker fiable", "Compatible Android & iPhone"],
    args_en: ["Best ANC value for money", "Trusted Anker brand", "Android & iPhone compatible"],
    tags: ["écouteurs", "sans-fil", "anc", "anker"], trendScore: 92,
    keywords: ["écouteurs", "earbuds", "anc", "bluetooth", "anker", "soundcore"],
  },
  {
    id: "tg-02",
    name_fr: "Anker 733 MagGo — Chargeur 3-en-1 MagSafe 65W",
    name_en: "Anker 733 MagGo — 3-in-1 MagSafe Charger 65W",
    categorySlug: "tech-gadgets", price: 79.99, cost: 0,
    amazonAsin: "B09BVYD5JN",
    supplierUrl: amz("B09BVYD5JN"),
    photoKeyword: "anker 733 maggo 3 in 1 wireless charger magsafe",
    short_fr: "Charge iPhone, AirPods et Apple Watch simultanément. 65W GaN intégré.",
    short_en: "Charges iPhone, AirPods and Apple Watch simultaneously. 65W GaN built-in.",
    desc_fr: "<p>Le chargeur 3-en-1 Anker MagGo charge votre iPhone (MagSafe 15W), vos AirPods et votre Apple Watch en même temps. Le chargeur mural 65W GaN est intégré — aucun adaptateur supplémentaire.</p>",
    desc_en: "<p>Anker MagGo 3-in-1 charges your iPhone (MagSafe 15W), AirPods, and Apple Watch simultaneously. 65W GaN wall charger built-in — no extra adapter needed.</p>",
    benefits_fr: ["MagSafe 15W certifié Apple", "Apple Watch & AirPods", "65W GaN intégré", "Design compact bureau", "Compatible iPhone 12 et +"],
    benefits_en: ["Apple-certified MagSafe 15W", "Apple Watch & AirPods", "65W GaN built-in", "Compact desk design", "iPhone 12 and newer"],
    args_fr: ["Remplace 3 chargeurs", "Bureau rangé instantanément", "Cadeau premium idéal"],
    args_en: ["Replaces 3 chargers", "Instant desk cleanup", "Perfect premium gift"],
    tags: ["chargeur", "magsafe", "iphone", "anker"], trendScore: 88,
    keywords: ["chargeur", "charger", "magsafe", "iphone", "apple watch", "anker"],
  },
  {
    id: "tg-03",
    name_fr: "Baseus Power Bank 20000mAh 65W USB-C",
    name_en: "Baseus Power Bank 20000mAh 65W USB-C",
    categorySlug: "tech-gadgets", price: 44.99, cost: 0,
    amazonAsin: "B09N3ZXS25",
    supplierUrl: amz("B09N3ZXS25"),
    photoKeyword: "baseus power bank 20000mah 65w usb-c portable",
    short_fr: "Charge un laptop, 2 téléphones simultanément. 65W sortie max.",
    short_en: "Charges a laptop + 2 phones simultaneously. 65W max output.",
    desc_fr: "<p>La batterie externe Baseus 20000mAh est la plus polyvalente du marché. 65W en sortie USB-C pour charger un MacBook ou PC portable, plus 2 autres appareils en même temps via USB-A.</p><p>Écran LED affichage précis du pourcentage restant.</p>",
    desc_en: "<p>The Baseus 20000mAh power bank is the most versatile on the market. 65W USB-C output to charge a MacBook or laptop, plus 2 other devices simultaneously via USB-A.</p>",
    benefits_fr: ["65W charge laptop & téléphone", "20000mAh — 4 charges iPhone", "3 ports simultanés", "Écran LED précis", "Charge rapide PD"],
    benefits_en: ["65W charges laptop & phone", "20000mAh — 4 iPhone charges", "3 simultaneous ports", "Precise LED display", "PD fast charge"],
    args_fr: ["Indispensable en voyage", "Charge même les MacBook", "Baseus = fiabilité prouvée"],
    args_en: ["Travel essential", "Charges even MacBooks", "Proven Baseus reliability"],
    tags: ["batterie", "power-bank", "usb-c", "baseus"], trendScore: 85,
    keywords: ["batterie", "power bank", "usb-c", "baseus", "laptop", "portable"],
  },
  {
    id: "tg-04",
    name_fr: "Logitech MX Master 3S — Souris Sans Fil Silencieuse",
    name_en: "Logitech MX Master 3S — Silent Wireless Mouse",
    categorySlug: "tech-gadgets", price: 99.99, cost: 0,
    amazonAsin: "B09HM94VDS",
    supplierUrl: amz("B09HM94VDS"),
    photoKeyword: "logitech mx master 3s wireless mouse silent",
    short_fr: "La souris préférée des créatifs. 8000 DPI, boutons silencieux, charge USB-C.",
    short_en: "The creatives' favourite mouse. 8000 DPI, silent clicks, USB-C charging.",
    desc_fr: "<p>La Logitech MX Master 3S est unanimement reconnue comme la meilleure souris sans fil du marché. Capteur 8000 DPI ultra-précis, molette MagSpeed électromagnétique, et boutons 90% plus silencieux.</p><p>Compatible Windows, Mac et Linux. Charge USB-C.</p>",
    desc_en: "<p>The Logitech MX Master 3S is universally recognized as the best wireless mouse on the market. Ultra-precise 8000 DPI sensor, MagSpeed electromagnetic scroll wheel, and 90% quieter buttons.</p>",
    benefits_fr: ["8000 DPI ultra-précis", "Molette MagSpeed rapide", "Boutons 90% silencieux", "Charge USB-C", "Connexion multi-appareils"],
    benefits_en: ["Ultra-precise 8000 DPI", "Fast MagSpeed wheel", "90% quieter clicks", "USB-C charging", "Multi-device connection"],
    args_fr: ["Standard professionnel mondial", "Compatible Mac & PC", "Autonomie 70 jours"],
    args_en: ["Global professional standard", "Mac & PC compatible", "70-day battery"],
    tags: ["souris", "logitech", "sans-fil", "bureau"], trendScore: 94,
    keywords: ["souris", "mouse", "logitech", "mx master", "sans-fil", "wireless"],
  },
  {
    id: "tg-05",
    name_fr: "TP-Link Tapo C200 — Caméra IP WiFi 360° 1080P",
    name_en: "TP-Link Tapo C200 — 360° WiFi Camera 1080P",
    categorySlug: "tech-gadgets", price: 29.99, cost: 0,
    amazonAsin: "B082Z11BFV",
    supplierUrl: amz("B082Z11BFV"),
    photoKeyword: "tp-link tapo c200 camera ip wifi 360 1080p",
    short_fr: "Surveillance intérieure 1080P, vision nocturne 9m, rotation 360°, alertes smartphone.",
    short_en: "Indoor 1080P surveillance, 9m night vision, 360° rotation, smartphone alerts.",
    desc_fr: "<p>La Tapo C200 est la caméra de surveillance intérieure la plus vendue en France. Résolution Full HD 1080P, rotation pan/tilt 360°, vision nocturne infrarouge jusqu'à 9 mètres.</p><p>Alertes de mouvement instantanées sur smartphone. Compatible Alexa et Google Home.</p>",
    desc_en: "<p>The Tapo C200 is France's best-selling indoor security camera. Full HD 1080P resolution, 360° pan/tilt rotation, infrared night vision up to 9 metres.</p>",
    benefits_fr: ["Full HD 1080P", "Rotation pan/tilt 360°", "Vision nocturne 9m", "Alertes mouvement", "Alexa & Google Home"],
    benefits_en: ["Full HD 1080P", "360° pan/tilt rotation", "9m night vision", "Motion alerts", "Alexa & Google Home"],
    args_fr: ["#1 vente caméra intérieure FR", "Installation 5 minutes", "Pas d'abonnement requis"],
    args_en: ["#1 selling indoor camera FR", "5-minute setup", "No subscription required"],
    tags: ["caméra", "sécurité", "wifi", "tp-link"], trendScore: 90,
    keywords: ["caméra", "camera", "surveillance", "wifi", "tp-link", "tapo"],
  },
  {
    id: "tg-06",
    name_fr: "Amazon Echo Dot 5 — Enceinte Connectée Alexa",
    name_en: "Amazon Echo Dot 5 — Smart Speaker with Alexa",
    categorySlug: "tech-gadgets", price: 54.99, cost: 0,
    amazonAsin: "B09B8YWXDF",
    supplierUrl: amz("B09B8YWXDF"),
    photoKeyword: "amazon echo dot 5 smart speaker alexa",
    short_fr: "Son amélioré, capteur température, assistant vocal Alexa, contrôle maison connectée.",
    short_en: "Improved sound, temperature sensor, Alexa voice assistant, smart home control.",
    desc_fr: "<p>L'Echo Dot 5ème génération offre un son plus riche et plus profond que jamais. Intègre un capteur de température ambiante et l'assistant vocal Alexa pour contrôler toute votre maison connectée.</p>",
    desc_en: "<p>The 5th gen Echo Dot delivers richer, deeper sound than ever. Includes an ambient temperature sensor and Alexa voice assistant to control your entire smart home.</p>",
    benefits_fr: ["Son riche graves améliorés", "Capteur température intégré", "Alexa — contrôle vocal total", "Compatible 100+ appareils", "Mode ne pas déranger"],
    benefits_en: ["Rich improved bass sound", "Built-in temperature sensor", "Alexa — full voice control", "100+ device compatible", "Do not disturb mode"],
    args_fr: ["Meilleure entrée maison connectée", "Amazon — marque de confiance", "Cadeau idéal"],
    args_en: ["Best smart home entry point", "Amazon — trusted brand", "Perfect gift"],
    tags: ["enceinte", "alexa", "amazon", "connecté"], trendScore: 89,
    keywords: ["echo dot", "alexa", "enceinte", "speaker", "amazon", "connecté"],
  },

  // ── maison-intelligente ───────────────────────────────────────────────────────
  {
    id: "mi-01",
    name_fr: "Philips Hue White — Pack 3 Ampoules E27 Connectées",
    name_en: "Philips Hue White — 3-Pack E27 Smart Bulbs",
    categorySlug: "maison-intelligente", price: 44.99, cost: 0,
    amazonAsin: "B07PNBQYTS",
    supplierUrl: amz("B07PNBQYTS"),
    photoKeyword: "philips hue white e27 smart bulb pack 3",
    short_fr: "Contrôle vocal Alexa/Google, programmation horaire, ambiance personnalisée.",
    short_en: "Alexa/Google voice control, scheduling, personalised ambiance.",
    desc_fr: "<p>Les ampoules Philips Hue sont la référence absolue de l'éclairage connecté. Ce pack de 3 ampoules E27 se pilote via l'app Hue, Alexa ou Google Home. Programmation d'horaires, scènes lumineuses et routines automatisées.</p>",
    desc_en: "<p>Philips Hue bulbs are the absolute reference for smart lighting. This pack of 3 E27 bulbs is controlled via the Hue app, Alexa, or Google Home. Schedule programming, light scenes, and automated routines.</p>",
    benefits_fr: ["Contrôle Alexa & Google", "Programmation horaire", "Durée de vie 25 000h", "Gradation 1%-100%", "Compatible Hue Bridge"],
    benefits_en: ["Alexa & Google control", "Schedule programming", "25,000h lifespan", "1%-100% dimming", "Hue Bridge compatible"],
    args_fr: ["Standard maison connectée", "Philips = qualité garantie", "Économise 80% énergie"],
    args_en: ["Smart home standard", "Philips = guaranteed quality", "Saves 80% energy"],
    tags: ["ampoule", "philips", "hue", "connectée"], trendScore: 87,
    keywords: ["ampoule", "bulb", "philips", "hue", "connectée", "alexa"],
  },
  {
    id: "mi-02",
    name_fr: "Kasa Smart HS100 — Prise Connectée WiFi",
    name_en: "Kasa Smart HS100 — Smart WiFi Plug",
    categorySlug: "maison-intelligente", price: 15.99, cost: 0,
    amazonAsin: "B0152WLWSA",
    supplierUrl: amz("B0152WLWSA"),
    photoKeyword: "kasa smart plug wifi hs100 tp-link",
    short_fr: "Rendez n'importe quel appareil connecté. Contrôle à distance, programmation, sans hub.",
    short_en: "Make any device smart. Remote control, scheduling, no hub required.",
    desc_fr: "<p>La prise Kasa HS100 transforme instantanément n'importe quel appareil électrique en appareil connecté. Contrôlez à distance via smartphone, programmez des horaires ou automatisez via Alexa et Google Home. Aucun hub requis.</p>",
    desc_en: "<p>The Kasa HS100 instantly transforms any electrical device into a smart device. Control remotely via smartphone, schedule timers, or automate via Alexa and Google Home. No hub required.</p>",
    benefits_fr: ["Aucun hub requis", "Contrôle à distance", "Programmation horaire", "Alexa & Google Home", "Consommation énergie visible"],
    benefits_en: ["No hub required", "Remote control", "Schedule timer", "Alexa & Google Home", "Energy monitoring"],
    args_fr: ["Le meilleur rapport qualité/prix", "Fonctionne avec tout", "Installation 2 minutes"],
    args_en: ["Best value for money", "Works with everything", "2-minute setup"],
    tags: ["prise", "connectée", "wifi", "kasa"], trendScore: 83,
    keywords: ["prise", "plug", "connectée", "wifi", "kasa", "tp-link"],
  },
  {
    id: "mi-03",
    name_fr: "Meross Smart Thermostat — Thermostat Connecté WiFi",
    name_en: "Meross Smart Thermostat — WiFi Smart Thermostat",
    categorySlug: "maison-intelligente", price: 39.99, cost: 0,
    amazonAsin: "B09L6DSLGQ",
    supplierUrl: amz("B09L6DSLGQ"),
    photoKeyword: "meross smart thermostat wifi connected home",
    short_fr: "Contrôlez votre chauffage à distance. Économisez jusqu'à 31% sur votre facture.",
    short_en: "Control your heating remotely. Save up to 31% on your energy bill.",
    desc_fr: "<p>Le thermostat Meross permet de contrôler votre chaudière ou radiateur électrique depuis votre smartphone, partout dans le monde. Programmation intelligente, détection d'absence et intégration Alexa/Google Home.</p><p>Économies réelles sur la facture d'énergie dès le premier mois.</p>",
    desc_en: "<p>The Meross thermostat lets you control your boiler or electric heater from your smartphone, anywhere in the world. Smart scheduling, away detection, and Alexa/Google Home integration.</p>",
    benefits_fr: ["Contrôle à distance mondial", "Économies jusqu'à 31%", "Détection d'absence auto", "Alexa & Google Home", "Installation sans électricien"],
    benefits_en: ["Worldwide remote control", "Savings up to 31%", "Auto away detection", "Alexa & Google Home", "No electrician needed"],
    args_fr: ["Rentabilisé en 2 mois", "Compatible toutes chaudières", "Meross = fiable & abordable"],
    args_en: ["Pays for itself in 2 months", "Compatible all boilers", "Meross = reliable & affordable"],
    tags: ["thermostat", "chauffage", "connecté", "meross"], trendScore: 81,
    keywords: ["thermostat", "chauffage", "heating", "meross", "connecté", "wifi"],
  },
  {
    id: "mi-04",
    name_fr: "Govee RGBIC — Ruban LED 10m Connecté WiFi",
    name_en: "Govee RGBIC — 10m Connected WiFi LED Strip",
    categorySlug: "maison-intelligente", price: 34.99, cost: 0,
    amazonAsin: "B094ZBFVD6",
    supplierUrl: amz("B094ZBFVD6"),
    photoKeyword: "govee rgbic led strip 10m wifi alexa",
    short_fr: "Effets multicolores simultanés, sync musique, contrôle Alexa & Google, app intuitive.",
    short_en: "Simultaneous multicolour effects, music sync, Alexa & Google control, intuitive app.",
    desc_fr: "<p>Le ruban LED Govee RGBIC permet d'afficher plusieurs couleurs simultanément grâce à la technologie IC individuelle. Synchronisation musicale en temps réel, 64 effets préréglés et contrôle vocal via Alexa ou Google Home.</p>",
    desc_en: "<p>Govee RGBIC LED strip displays multiple colours simultaneously thanks to individual IC technology. Real-time music synchronisation, 64 preset effects, and voice control via Alexa or Google Home.</p>",
    benefits_fr: ["Multicolore simultané RGBIC", "Sync musique temps réel", "64 effets préréglés", "App Govee intuitive", "Coupe et rallonge possible"],
    benefits_en: ["Simultaneous RGBIC multicolour", "Real-time music sync", "64 preset effects", "Intuitive Govee app", "Cuttable and extendable"],
    args_fr: ["Transforme n'importe quelle pièce", "TikTok/gaming esthétique", "Govee = référence LED"],
    args_en: ["Transforms any room", "TikTok/gaming aesthetic", "Govee = LED reference"],
    tags: ["led", "ruban", "govee", "rgbic"], trendScore: 86,
    keywords: ["led", "ruban", "strip", "govee", "rgbic", "wifi", "alexa"],
  },
  {
    id: "mi-05",
    name_fr: "Eufy RoboVac X8 — Robot Aspirateur 2000Pa WiFi",
    name_en: "Eufy RoboVac X8 — Robot Vacuum 2000Pa WiFi",
    categorySlug: "maison-intelligente", price: 249.99, cost: 0,
    amazonAsin: "B09CCC9ZC8",
    supplierUrl: amz("B09CCC9ZC8"),
    photoKeyword: "eufy robovac x8 robot vacuum 2000pa wifi mapping",
    short_fr: "Aspiration twin-turbine 2000Pa, cartographie laser, vidage automatique, silencieux.",
    short_en: "Twin-turbine 2000Pa suction, laser mapping, auto-empty, ultra-quiet.",
    desc_fr: "<p>Le RoboVac X8 d'Eufy utilise deux turbines pour une aspiration 2000Pa inégalée. Cartographie laser précise de votre domicile, programmation par pièces et base de vidage automatique en option.</p><p>Le robot aspirateur qui remplace vraiment l'aspirateur traditionnel.</p>",
    desc_en: "<p>Eufy's RoboVac X8 uses twin turbines for unmatched 2000Pa suction. Precise laser mapping of your home, room-by-room scheduling, and optional auto-empty base.</p>",
    benefits_fr: ["2000Pa twin-turbine", "Cartographie laser précise", "Planning par pièce", "Ultra-silencieux 68dB", "Compatible Alexa & Google"],
    benefits_en: ["2000Pa twin-turbine", "Precise laser mapping", "Room-by-room scheduling", "Ultra-quiet 68dB", "Alexa & Google compatible"],
    args_fr: ["Remplace l'aspirateur classique", "Eufy = sous-marque Anker", "Retour base automatique"],
    args_en: ["Replaces traditional vacuum", "Eufy = Anker sub-brand", "Automatic dock return"],
    tags: ["robot", "aspirateur", "eufy", "wifi"], trendScore: 88,
    keywords: ["robot", "aspirateur", "vacuum", "eufy", "wifi", "cartographie"],
  },
  {
    id: "mi-06",
    name_fr: "Sonos Era 100 — Enceinte WiFi Multiroom Stéréo",
    name_en: "Sonos Era 100 — Stereo WiFi Multiroom Speaker",
    categorySlug: "maison-intelligente", price: 249.99, cost: 0,
    amazonAsin: "B0BW5PNSHV",
    supplierUrl: amz("B0BW5PNSHV"),
    photoKeyword: "sonos era 100 wifi speaker multiroom stereo",
    short_fr: "Son stéréo vrai, Bluetooth + WiFi, AirPlay 2, multiroom, Alexa intégré.",
    short_en: "True stereo sound, Bluetooth + WiFi, AirPlay 2, multiroom, built-in Alexa.",
    desc_fr: "<p>Le Sonos Era 100 est la nouvelle référence en enceinte connectée avec son stéréo vrai (deux tweeters inclinés). Connexion WiFi et Bluetooth simultanée, AirPlay 2, multiroom Sonos et Alexa intégré.</p>",
    desc_en: "<p>The Sonos Era 100 is the new reference in connected speakers with true stereo sound (two angled tweeters). Simultaneous WiFi and Bluetooth, AirPlay 2, Sonos multiroom, and built-in Alexa.</p>",
    benefits_fr: ["Son stéréo vrai", "WiFi + Bluetooth simultané", "AirPlay 2 certifié", "Multiroom Sonos", "Alexa intégré"],
    benefits_en: ["True stereo sound", "Simultaneous WiFi + Bluetooth", "AirPlay 2 certified", "Sonos multiroom", "Built-in Alexa"],
    args_fr: ["Premium audio — prix justifié", "Ecosystème Sonos évolutif", "Design award-winning"],
    args_en: ["Premium audio — price justified", "Scalable Sonos ecosystem", "Award-winning design"],
    tags: ["enceinte", "sonos", "wifi", "multiroom"], trendScore: 85,
    keywords: ["enceinte", "speaker", "sonos", "wifi", "multiroom", "airplay"],
  },

  // ── sport-fitness ─────────────────────────────────────────────────────────────
  {
    id: "sf-01",
    name_fr: "Theragun Mini — Pistolet Massage Professionnel",
    name_en: "Theragun Mini — Professional Massage Gun",
    categorySlug: "sport-fitness", price: 149.99, cost: 0,
    amazonAsin: "B0C4HPFDF2",
    supplierUrl: amz("B0C4HPFDF2"),
    photoKeyword: "theragun mini massage gun professional recovery",
    short_fr: "Récupération musculaire professionnelle. 150 min autonomie, 3 vitesses, format poche.",
    short_en: "Professional muscle recovery. 150 min battery, 3 speeds, pocket-sized.",
    desc_fr: "<p>Le Theragun Mini est le pistolet de massage de référence en format compact. Amplitude de 12mm, 3 vitesses réglables et 150 minutes d'autonomie pour une récupération musculaire profonde après l'effort.</p><p>La marque utilisée par les athlètes professionnels, en version accessible.</p>",
    desc_en: "<p>The Theragun Mini is the reference massage gun in compact format. 12mm amplitude, 3 adjustable speeds, and 150 minutes battery for deep muscle recovery after exercise.</p>",
    benefits_fr: ["Amplitude 12mm profonde", "150 min autonomie", "3 vitesses précises", "Format poche compact", "4 embouts inclus"],
    benefits_en: ["12mm deep amplitude", "150 min battery", "3 precise speeds", "Compact pocket size", "4 attachments included"],
    args_fr: ["Theragun = référence mondiale", "Utilisé par les pros", "Récupère 2x plus vite"],
    args_en: ["Theragun = world reference", "Used by pros", "Recover 2x faster"],
    tags: ["massage", "récupération", "theragun", "sport"], trendScore: 91,
    keywords: ["massage", "gun", "theragun", "récupération", "recovery", "sport"],
  },
  {
    id: "sf-02",
    name_fr: "Garmin Forerunner 55 — Montre GPS Running",
    name_en: "Garmin Forerunner 55 — GPS Running Watch",
    categorySlug: "sport-fitness", price: 169.99, cost: 0,
    amazonAsin: "B092WQJLQQ",
    supplierUrl: amz("B092WQJLQQ"),
    photoKeyword: "garmin forerunner 55 gps running watch fitness",
    short_fr: "GPS précis, fréquence cardiaque, plans d'entraînement intégrés, 2 semaines autonomie.",
    short_en: "Precise GPS, heart rate, built-in training plans, 2-week battery.",
    desc_fr: "<p>La Garmin Forerunner 55 est la montre GPS running idéale pour débuter ou progresser. GPS intégré précis, capteur cardiaque au poignet, plans d'entraînement adaptatifs et 2 semaines d'autonomie en mode montre.</p>",
    desc_en: "<p>The Garmin Forerunner 55 is the ideal GPS running watch for beginners or those looking to progress. Precise built-in GPS, wrist heart rate sensor, adaptive training plans, and 2-week battery in watch mode.</p>",
    benefits_fr: ["GPS intégré précis", "Fréquence cardiaque poignet", "Plans entraînement intégrés", "2 semaines autonomie", "Résistance eau 5ATM"],
    benefits_en: ["Precise built-in GPS", "Wrist heart rate", "Built-in training plans", "2-week battery", "5ATM water resistance"],
    args_fr: ["Garmin = référence running", "Parfait débutant à intermédiaire", "Application Garmin Connect"],
    args_en: ["Garmin = running reference", "Perfect beginner to intermediate", "Garmin Connect app"],
    tags: ["montre", "gps", "running", "garmin"], trendScore: 89,
    keywords: ["montre", "watch", "gps", "running", "garmin", "forerunner"],
  },
  {
    id: "sf-03",
    name_fr: "Bowflex SelectTech 552 — Haltères Réglables 2-24kg",
    name_en: "Bowflex SelectTech 552 — Adjustable Dumbbells 2-24kg",
    categorySlug: "sport-fitness", price: 329.99, cost: 0,
    amazonAsin: "B001ARYU58",
    supplierUrl: amz("B001ARYU58"),
    photoKeyword: "bowflex selecttech 552 adjustable dumbbell set",
    short_fr: "15 poids en 1. De 2 à 24kg, sélection en 3 secondes. Remplace toute une salle de sport.",
    short_en: "15 weights in 1. From 2 to 24kg, select in 3 seconds. Replaces an entire gym.",
    desc_fr: "<p>Les haltères Bowflex SelectTech 552 remplacent 15 paires d'haltères en un seul appareil compact. Sélecteur rotatif pour passer de 2 à 24kg en 3 secondes. La solution home gym définitive.</p>",
    desc_en: "<p>Bowflex SelectTech 552 dumbbells replace 15 pairs of dumbbells in one compact unit. Rotary selector to go from 2 to 24kg in 3 seconds. The ultimate home gym solution.</p>",
    benefits_fr: ["15 poids en 1 appareil", "De 2 à 24kg", "Sélection 3 secondes", "Compact — 1 paire encombrement", "Garantie 2 ans"],
    benefits_en: ["15 weights in 1 unit", "From 2 to 24kg", "3-second selection", "Compact — 1 pair footprint", "2-year warranty"],
    args_fr: ["Économise 2000€ de matériel", "Bowflex = leader mondial", "S'adapte à tous niveaux"],
    args_en: ["Saves €2000 in equipment", "Bowflex = world leader", "Adapts to all levels"],
    tags: ["haltères", "home-gym", "bowflex", "fitness"], trendScore: 86,
    keywords: ["haltères", "dumbbells", "bowflex", "home gym", "fitness", "réglables"],
  },
  {
    id: "sf-04",
    name_fr: "Fitbit Charge 6 — Bracelet Fitness Cardio GPS",
    name_en: "Fitbit Charge 6 — Fitness Tracker with GPS & Cardio",
    categorySlug: "sport-fitness", price: 149.99, cost: 0,
    amazonAsin: "B0CDF7K9KS",
    supplierUrl: amz("B0CDF7K9KS"),
    photoKeyword: "fitbit charge 6 fitness tracker gps heart rate",
    short_fr: "GPS intégré, ECG, SpO2, suivi sommeil avancé, 7 jours autonomie.",
    short_en: "Built-in GPS, ECG, SpO2, advanced sleep tracking, 7-day battery.",
    desc_fr: "<p>Le Fitbit Charge 6 est le tracker fitness le plus complet de sa gamme de prix. GPS intégré sans smartphone, ECG pour détecter la fibrillation auriculaire, SpO2, et suivi du sommeil avec score détaillé.</p><p>Intégration Google Maps, YouTube Music et Google Wallet.</p>",
    desc_en: "<p>The Fitbit Charge 6 is the most complete fitness tracker in its price range. Built-in GPS without a smartphone, ECG to detect atrial fibrillation, SpO2, and sleep tracking with detailed score.</p>",
    benefits_fr: ["GPS sans smartphone", "ECG fibrillation auriculaire", "SpO2 saturation oxygène", "Suivi sommeil score", "7 jours autonomie"],
    benefits_en: ["GPS without smartphone", "ECG atrial fibrillation", "SpO2 oxygen saturation", "Sleep score tracking", "7-day battery"],
    args_fr: ["Fitbit = Google Health data", "Le plus complet < 200€", "Résistance eau 50m"],
    args_en: ["Fitbit = Google Health data", "Most complete under €200", "50m water resistance"],
    tags: ["fitbit", "tracker", "gps", "santé"], trendScore: 87,
    keywords: ["fitbit", "tracker", "fitness", "gps", "santé", "health"],
  },
  {
    id: "sf-05",
    name_fr: "Manduka PRO — Tapis Yoga Professionnel 6mm",
    name_en: "Manduka PRO — Professional Yoga Mat 6mm",
    categorySlug: "sport-fitness", price: 129.99, cost: 0,
    amazonAsin: "B001AT4JOG",
    supplierUrl: amz("B001AT4JOG"),
    photoKeyword: "manduka pro yoga mat professional 6mm",
    short_fr: "Le tapis yoga de référence. Garantie à vie, 6mm amorti, antidérapant total.",
    short_en: "The reference yoga mat. Lifetime guarantee, 6mm cushion, totally non-slip.",
    desc_fr: "<p>Le Manduka PRO est le tapis de yoga utilisé par les professeurs et pratiquants sérieux du monde entier. 6mm d'amorti dense, surface antidérapante parfaite même en session intense, et garantie à vie.</p>",
    desc_en: "<p>The Manduka PRO is the yoga mat used by teachers and serious practitioners worldwide. 6mm dense cushioning, perfect non-slip surface even in intense sessions, and lifetime guarantee.</p>",
    benefits_fr: ["Garantie à vie", "6mm amorti dense", "Antidérapant total", "Écologique — sans PVC", "Largeur 61cm confort"],
    benefits_en: ["Lifetime guarantee", "6mm dense cushioning", "Totally non-slip", "Eco — PVC-free", "61cm comfort width"],
    args_fr: ["Dernier tapis que tu achètes", "Manduka = standard pro mondial", "Zéro glissement garanti"],
    args_en: ["Last mat you'll ever buy", "Manduka = world pro standard", "Zero slipping guaranteed"],
    tags: ["yoga", "tapis", "manduka", "sport"], trendScore: 82,
    keywords: ["yoga", "tapis", "mat", "manduka", "fitness", "antidérapant"],
  },
  {
    id: "sf-06",
    name_fr: "WalkingPad R2 — Tapis de Marche Pliable Sous Bureau",
    name_en: "WalkingPad R2 — Foldable Under-Desk Walking Pad",
    categorySlug: "sport-fitness", price: 379.99, cost: 0,
    amazonAsin: "B09R6FVK8S",
    supplierUrl: amz("B09R6FVK8S"),
    photoKeyword: "walkingpad r2 treadmill foldable under desk office",
    short_fr: "Marchez en travaillant. Pliable en 3s, 0.5-6km/h, ultra-silencieux, télécommande.",
    short_en: "Walk while working. Folds in 3s, 0.5-6km/h, ultra-quiet, remote control.",
    desc_fr: "<p>Le WalkingPad R2 révolutionne le bureau debout en ajoutant le mouvement à votre journée de travail. Se plie en 3 secondes, vitesse 0.5 à 6km/h pour marcher en réunion Teams, ultra-silencieux pour les appels.</p>",
    desc_en: "<p>The WalkingPad R2 revolutionises the standing desk by adding movement to your workday. Folds in 3 seconds, speed 0.5 to 6km/h to walk during Teams meetings, ultra-quiet for calls.</p>",
    benefits_fr: ["Pliable en 3 secondes", "Vitesse 0.5-6km/h", "Ultra-silencieux < 75dB", "Télécommande incluse", "App WalkingPad"],
    benefits_en: ["Folds in 3 seconds", "Speed 0.5-6km/h", "Ultra-quiet < 75dB", "Remote included", "WalkingPad app"],
    args_fr: ["10 000 pas sans quitter son bureau", "Télétravail actif", "WalkingPad = leader mondial"],
    args_en: ["10,000 steps without leaving your desk", "Active remote work", "WalkingPad = world leader"],
    tags: ["tapis", "marche", "bureau", "walkingpad"], trendScore: 88,
    keywords: ["tapis", "marche", "walking", "bureau", "desk", "walkingpad", "télétravail"],
  },

  // ── bureau-productivite ───────────────────────────────────────────────────────
  {
    id: "bp-01",
    name_fr: "LG 27UN850 — Écran 4K 27\" USB-C 96W IPS",
    name_en: "LG 27UN850 — 27\" 4K USB-C 96W IPS Monitor",
    categorySlug: "bureau-productivite", price: 449.99, cost: 0,
    amazonAsin: "B08ZJCTWQJ",
    supplierUrl: amz("B08ZJCTWQJ"),
    photoKeyword: "lg 27un850 4k monitor 27 usb-c 96w ips",
    short_fr: "4K IPS, USB-C 96W (charge MacBook), AMD FreeSync, HDR400. Le monitor HomeOffice parfait.",
    short_en: "4K IPS, USB-C 96W (charges MacBook), AMD FreeSync, HDR400. Perfect home office monitor.",
    desc_fr: "<p>Le LG 27UN850 est le moniteur de référence pour le travail en haute résolution. 4K IPS avec couverture 99% sRGB, USB-C 96W qui charge votre MacBook Pro en un câble, et HDR400 pour les contenus.</p>",
    desc_en: "<p>The LG 27UN850 is the reference monitor for high-resolution work. 4K IPS with 99% sRGB coverage, USB-C 96W that charges your MacBook Pro with one cable, and HDR400 for content.</p>",
    benefits_fr: ["4K UHD 3840x2160", "USB-C 96W charge MacBook", "99% sRGB couverture", "HDR400 certifié", "Réglable hauteur/pivot"],
    benefits_en: ["4K UHD 3840x2160", "USB-C 96W charges MacBook", "99% sRGB coverage", "HDR400 certified", "Height/pivot adjustable"],
    args_fr: ["Un câble USB-C = tout", "LG = référence moniteur pro", "Compatible Mac & PC"],
    args_en: ["One USB-C cable = everything", "LG = pro monitor reference", "Mac & PC compatible"],
    tags: ["moniteur", "4k", "lg", "usb-c"], trendScore: 88,
    keywords: ["moniteur", "monitor", "4k", "lg", "usb-c", "macbook", "bureau"],
  },
  {
    id: "bp-02",
    name_fr: "Keychron K2 Pro — Clavier Mécanique Sans Fil",
    name_en: "Keychron K2 Pro — Wireless Mechanical Keyboard",
    categorySlug: "bureau-productivite", price: 99.99, cost: 0,
    amazonAsin: "B0BK5J9KTD",
    supplierUrl: amz("B0BK5J9KTD"),
    photoKeyword: "keychron k2 pro mechanical keyboard wireless bluetooth",
    short_fr: "Bluetooth 5.1 multi-appareils, rétroéclairage RGB, compatible Mac & Windows.",
    short_en: "Bluetooth 5.1 multi-device, RGB backlight, Mac & Windows compatible.",
    desc_fr: "<p>Le Keychron K2 Pro est devenu le clavier mécanique de référence pour les développeurs et créatifs. Bluetooth 5.1 avec connexion simultanée 3 appareils, switches Gateron hotswap, rétroéclairage RGB et compatibilité Mac/Windows.</p>",
    desc_en: "<p>The Keychron K2 Pro has become the reference mechanical keyboard for developers and creatives. Bluetooth 5.1 with simultaneous 3-device connection, Gateron hotswap switches, RGB backlight, and Mac/Windows compatibility.</p>",
    benefits_fr: ["Bluetooth 3 appareils simultanés", "Switches hotswap", "RGB rétroéclairage", "Mac & Windows natif", "Autonomie 4000mAh"],
    benefits_en: ["Bluetooth 3 simultaneous devices", "Hotswap switches", "RGB backlight", "Native Mac & Windows", "4000mAh battery"],
    args_fr: ["Keychron = standard dev mondial", "Customisable switches", "Construit pour durer"],
    args_en: ["Keychron = world dev standard", "Customisable switches", "Built to last"],
    tags: ["clavier", "mécanique", "keychron", "bluetooth"], trendScore: 90,
    keywords: ["clavier", "keyboard", "keychron", "mécanique", "bluetooth", "wireless"],
  },
  {
    id: "bp-03",
    name_fr: "Flexispot E7 — Bureau Assis-Debout Électrique 160x80cm",
    name_en: "Flexispot E7 — Electric Sit-Stand Desk 160x80cm",
    categorySlug: "bureau-productivite", price: 499.99, cost: 0,
    amazonAsin: "B08B2TF2FJ",
    supplierUrl: amz("B08B2TF2FJ"),
    photoKeyword: "flexispot e7 standing desk electric sit stand",
    short_fr: "Double moteur silencieux, plateau 160x80, 4 hauteurs mémorisées, charge 125kg.",
    short_en: "Silent dual motor, 160x80 top, 4 saved heights, 125kg load capacity.",
    desc_fr: "<p>Le Flexispot E7 est le bureau assis-debout électrique le plus populaire en Europe. Double moteur ultra-silencieux (< 50dB), plateau 160x80cm, 4 positions mémorisées et détection anti-collision.</p><p>Transformez votre bureau en station de travail ergonomique.</p>",
    desc_en: "<p>The Flexispot E7 is the most popular electric sit-stand desk in Europe. Ultra-quiet dual motor (< 50dB), 160x80cm top, 4 saved positions, and anti-collision detection.</p>",
    benefits_fr: ["Double moteur < 50dB", "4 hauteurs mémorisées", "Charge 125kg", "Anti-collision sécurité", "Plateau 160x80cm"],
    benefits_en: ["Dual motor < 50dB", "4 saved heights", "125kg load capacity", "Anti-collision safety", "160x80cm top"],
    args_fr: ["Dos sauvegardé dès la 1ère semaine", "Flexispot = leader EU", "Compatible tout plateau"],
    args_en: ["Back saved from week 1", "Flexispot = EU leader", "Compatible all tops"],
    tags: ["bureau", "assis-debout", "flexispot", "ergonomie"], trendScore: 87,
    keywords: ["bureau", "desk", "assis-debout", "flexispot", "ergonomie", "standing"],
  },
  {
    id: "bp-04",
    name_fr: "Elgato Key Light — Panneau LED Studio 2800 Lumens",
    name_en: "Elgato Key Light — Studio LED Panel 2800 Lumens",
    categorySlug: "bureau-productivite", price: 199.99, cost: 0,
    amazonAsin: "B07L755X9G",
    supplierUrl: amz("B07L755X9G"),
    photoKeyword: "elgato key light studio led panel streaming",
    short_fr: "Éclairage pro pour visio, streaming, contenu. 2800 lumens, couleur ajustable, app.",
    short_en: "Pro lighting for video calls, streaming, content. 2800 lumens, adjustable colour, app.",
    desc_fr: "<p>L'Elgato Key Light est la référence absolue de l'éclairage bureau pour les professionnels. 2800 lumens, température de couleur réglable (2900K-7000K), contrôle via app ou Stream Deck. Idéal Zoom, Teams, YouTube, streaming.</p>",
    desc_en: "<p>The Elgato Key Light is the absolute reference for professional desk lighting. 2800 lumens, adjustable colour temperature (2900K-7000K), control via app or Stream Deck. Ideal for Zoom, Teams, YouTube, streaming.</p>",
    benefits_fr: ["2800 lumens puissant", "Température 2900K-7000K", "App + Stream Deck", "Support articulé solide", "Zéro éblouissement"],
    benefits_en: ["Powerful 2800 lumens", "2900K-7000K temperature", "App + Stream Deck", "Solid articulated stand", "Zero glare"],
    args_fr: ["Elgato = standard streamers/créateurs", "Visio professionnelle garantie", "Compatible tout setup"],
    args_en: ["Elgato = streamer/creator standard", "Professional video calls guaranteed", "Compatible any setup"],
    tags: ["lumière", "elgato", "streaming", "bureau"], trendScore: 85,
    keywords: ["lumière", "light", "elgato", "streaming", "bureau", "visio", "studio"],
  },
  {
    id: "bp-05",
    name_fr: "Logitech Brio 4K — Webcam 4K HDR USB-C",
    name_en: "Logitech Brio 4K — 4K HDR USB-C Webcam",
    categorySlug: "bureau-productivite", price: 199.99, cost: 0,
    amazonAsin: "B01N5UOYC4",
    supplierUrl: amz("B01N5UOYC4"),
    photoKeyword: "logitech brio 4k webcam hdr usb-c streaming",
    short_fr: "La meilleure webcam du marché. 4K HDR, correction lumière automatique, Windows Hello.",
    short_en: "The best webcam on the market. 4K HDR, auto light correction, Windows Hello.",
    desc_fr: "<p>La Logitech Brio est la webcam de référence absolue pour les professionnels. 4K Ultra HD avec HDR, correction automatique de la lumière RightLight 3, et compatibilité Windows Hello pour l'authentification faciale.</p>",
    desc_en: "<p>The Logitech Brio is the absolute reference webcam for professionals. 4K Ultra HD with HDR, RightLight 3 automatic light correction, and Windows Hello compatibility for facial authentication.</p>",
    benefits_fr: ["4K Ultra HD HDR", "RightLight 3 auto", "Windows Hello facial", "Champ vision 90°", "USB-C & USB-A"],
    benefits_en: ["4K Ultra HD HDR", "Auto RightLight 3", "Windows Hello facial", "90° field of view", "USB-C & USB-A"],
    args_fr: ["Logitech Brio = standard absolu", "Télétravail professionnel", "Zoom/Teams toujours parfait"],
    args_en: ["Logitech Brio = absolute standard", "Professional remote work", "Zoom/Teams always perfect"],
    tags: ["webcam", "4k", "logitech", "brio"], trendScore: 86,
    keywords: ["webcam", "logitech", "brio", "4k", "streaming", "visio"],
  },
  {
    id: "bp-06",
    name_fr: "Herman Miller Aeron — Chaise Ergonomique Taille B",
    name_en: "Herman Miller Aeron — Ergonomic Chair Size B",
    categorySlug: "bureau-productivite", price: 1299.99, cost: 0,
    amazonAsin: "B00MLSS1SW",
    supplierUrl: amz("B00MLSS1SW"),
    photoKeyword: "herman miller aeron ergonomic office chair size b",
    short_fr: "La chaise de bureau #1 mondiale. Soutien lombaire PostureFit SL, 8h confort garanti.",
    short_en: "The world's #1 office chair. PostureFit SL lumbar support, 8h guaranteed comfort.",
    desc_fr: "<p>La Herman Miller Aeron est unanimement reconnue comme la meilleure chaise de bureau au monde. PostureFit SL soutient l'ensemble du dos, matière 8Z Pellicle aérée et réglages 8 points pour une ergonomie parfaite.</p><p>Garantie 12 ans. Un investissement rentabilisé en quelques semaines.</p>",
    desc_en: "<p>The Herman Miller Aeron is universally recognised as the world's best office chair. PostureFit SL supports the entire back, breathable 8Z Pellicle material, and 8-point adjustments for perfect ergonomics.</p><p>12-year warranty. An investment that pays off in weeks.</p>",
    benefits_fr: ["PostureFit SL dos complet", "Matière 8Z aérée", "8 réglages précis", "Garantie 12 ans", "Recyclable à 91%"],
    benefits_en: ["PostureFit SL full back support", "Breathable 8Z Pellicle", "8 precise adjustments", "12-year warranty", "91% recyclable"],
    args_fr: ["#1 mondiale — unanimement", "Dos sauvé définitivement", "Herman Miller = référence absolue"],
    args_en: ["#1 worldwide — unanimous", "Back saved for good", "Herman Miller = absolute reference"],
    tags: ["chaise", "ergonomique", "herman-miller", "bureau"], trendScore: 93,
    keywords: ["chaise", "chair", "herman miller", "aeron", "ergonomique", "bureau"],
  },
];

export const CATEGORY_SLUGS = [
  "tech-gadgets",
  "maison-intelligente",
  "sport-fitness",
  "bureau-productivite",
];

export function matchTrendToCategories(trends: string[]): string[] {
  const map: Record<string, string[]> = {
    "tech-gadgets": ["tech", "gadget", "électronique", "audio", "bluetooth", "wifi", "speaker", "écouteur"],
    "maison-intelligente": ["maison", "home", "smart", "connecté", "enceinte", "lumière", "thermostat", "robot"],
    "sport-fitness": ["sport", "fitness", "yoga", "running", "gym", "massage", "santé", "tracker"],
    "bureau-productivite": ["bureau", "desk", "ergonomie", "travail", "remote", "webcam", "clavier", "monitor"],
  };
  const scored: Record<string, number> = {};
  for (const slug of CATEGORY_SLUGS) scored[slug] = 0;
  for (const trend of trends) {
    const t = trend.toLowerCase();
    for (const [slug, keywords] of Object.entries(map)) {
      if (keywords.some(k => t.includes(k))) scored[slug]++;
    }
  }
  return CATEGORY_SLUGS.sort((a, b) => (scored[b] || 0) - (scored[a] || 0));
}
