import type { ProductSignal } from "./prospectingTypes";

export const PRODUCT_SIGNALS: ProductSignal[] = [
  {
    id: "ceramic-led-table-lamp",
    label: "Lampe céramique nomade",
    domain: "maison",
    keywords: ["portable lamp", "ceramic lamp", "warm light", "interior gift"],
    priceBand: [89, 149],
    desirability: 88,
    giftability: 82,
    marginPotential: 74,
    saturationRisk: 34,
    seasonality: 78,
    visualPotential: 92,
  },
  {
    id: "travel-jewelry-case",
    label: "Étui bijoux de voyage",
    domain: "bijoux",
    keywords: ["travel jewelry case", "vegan leather", "gift for her", "minimal jewelry storage"],
    priceBand: [69, 119],
    desirability: 84,
    giftability: 94,
    marginPotential: 79,
    saturationRisk: 42,
    seasonality: 85,
    visualPotential: 88,
  },
  {
    id: "aluminum-charging-valet",
    label: "Valet de charge aluminium",
    domain: "tech",
    keywords: ["charging dock", "desk valet", "apple accessories", "minimal tech"],
    priceBand: [99, 169],
    desirability: 86,
    giftability: 84,
    marginPotential: 72,
    saturationRisk: 45,
    seasonality: 74,
    visualPotential: 90,
  },
  {
    id: "silk-sleep-mask",
    label: "Masque de sommeil soie",
    domain: "beaute",
    keywords: ["silk sleep mask", "night ritual", "beauty sleep", "premium wellness"],
    priceBand: [59, 99],
    desirability: 81,
    giftability: 88,
    marginPotential: 82,
    saturationRisk: 48,
    seasonality: 80,
    visualPotential: 83,
  },
  {
    id: "graphite-desk-tray",
    label: "Plateau bureau graphite",
    domain: "bureau",
    keywords: ["desk tray", "office organizer", "graphite desk", "work ritual"],
    priceBand: [79, 139],
    desirability: 78,
    giftability: 76,
    marginPotential: 77,
    saturationRisk: 31,
    seasonality: 71,
    visualPotential: 86,
  },
  {
    id: "weekend-cable-roll",
    label: "Trousse câbles weekend",
    domain: "voyage",
    keywords: ["cable organizer", "travel tech pouch", "premium travel accessories"],
    priceBand: [65, 115],
    desirability: 83,
    giftability: 81,
    marginPotential: 80,
    saturationRisk: 37,
    seasonality: 76,
    visualPotential: 82,
  },
];
